### ISSUE TITLE
Wrong responses for eth_getTransactionReceipt method on polygon

### ISSUE THREAD

**Issue by prostghost** [ledgerwatch/erigon#16944]
#### System information

Erigon version: v3.0.15

OS & Version: Linux

Chain/Network: polygon mainnet

#### Expected behaviour
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
    "blockNumber": "0x2fc15e0",
    "contractAddress": null,
    "cumulativeGasUsed": "0x0",
    "effectiveGasPrice": "0x1db1943c3",
    "from": "0x0000000000000000000000000000000000000000",
    "gasUsed": "0x0",
    "logs": [
      {
        "address": "0x0000000000000000000000000000000000001010",
        "topics": [
          "0xe6497e3ee548a3372136af2fcb0696db31fc6cf20260707645068bd3fe97f3c4",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x0000000000000000000000002ce910fbba65b454bbaf6a18c952a70f3bcd8299"
        ],
        "data": "0x0000000000000000000000000000000000000000000003a12d95cbbedbaf000000000000000000000000000000000000000000001cbfeb931a63433de7a508ff000000000000000000000000000000000000000000000035260b271eaddfeab300000000000000000000000000000000000000001cbfe7f1eccd777f0bf608ff0000000000000000000000000000000000000000000003d653a0f2dd898eeab3",
        "blockNumber": "0x2fc15e0",
        "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
        "transactionIndex": "0x0",
        "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
        "logIndex": "0x0",
        "removed": false
      },
      {
        "address": "0x0000000000000000000000000000000000001010",
        "topics": [
          "0x4e2ca0515ed1aef1395f66b5303bb5d6f1bf9d61a353fa53f73f8ac9973fa9f6",
          "0x0000000000000000000000007d1afa7b718fb893db30a3abc0cfc608aacfebb0",
          "0x0000000000000000000000002ce910fbba65b454bbaf6a18c952a70f3bcd8299"
        ],
        "data": "0x0000000000000000000000000000000000000000000003a12d95cbbedbaf0000000000000000000000000000000000000000000000000035260b271eaddfeab30000000000000000000000000000000000000000000003d653a0f2dd898eeab3",
        "blockNumber": "0x2fc15e0",
        "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
        "transactionIndex": "0x0",
        "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
        "logIndex": "0x1",
        "removed": false
      },
      {
        "address": "0xd9c7c4ed4b66858301d0cb28cc88bf655fe34861",
        "topics": [
          "0xec3afb067bce33c5a294470ec5b29e6759301cd3928550490c6d48816cdc2f5d",
          "0x0000000000000000000000007d1afa7b718fb893db30a3abc0cfc608aacfebb0",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x0000000000000000000000002ce910fbba65b454bbaf6a18c952a70f3bcd8299"
        ],
        "data": "0x0000000000000000000000000000000000000000000003a12d95cbbedbaf00000000000000000000000000000000000000000000000000000000000020109e41",
        "blockNumber": "0x2fc15e0",
        "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
        "transactionIndex": "0x0",
        "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
        "logIndex": "0x2",
        "removed": false
      }
    ],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000800100000000000008000000000000000080000000000000000000000000000000000000000800000000000000000000100000000000000000000000000000000000000000000000000000020000000000000010000000000000000000000040024000000000000000000000204000000000000000000000000000000000000000000000000000000000000000000000000000000004000000020000002000000000000000000000000000000800000108000000000000000000000002010000000000000000000000000000000080000000000100002",
    "status": "0x1",
    "to": "0x0000000000000000000000000000000000000000",
    "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
    "transactionIndex": "0x0",
    "type": "0x0"
  }
}
```

#### Actual behaviour
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
    "blockNumber": "0x2fc15e0",
    "contractAddress": null,
    "cumulativeGasUsed": "0x0",
    "effectiveGasPrice": "0x1db1943c3",
    "from": "0x0000000000000000000000000000000000000000",
    "gasUsed": "0x0",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status": "0x1",
    "to": "0x0000000000000000000000000000000000000000",
    "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
    "transactionIndex": "0x0",
    "type": "0x0"
  }
}
```

#### Steps to reproduce the behaviour
```
{
  "jsonrpc": "2.0",
  "method": "eth_getTransactionReceipt",
  "params": [
    "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb"
  ],
  "id": 1
}
```

#### Also there is a bug where node with v3.1.0-rc1 version has wrong logIndexes
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
    "blockNumber": "0x2fc15e0",
    "contractAddress": null,
    "cumulativeGasUsed": "0x0",
    "effectiveGasPrice": "0x1db1943c3",
    "from": "0x0000000000000000000000000000000000000000",
    "gasUsed": "0x0",
    "logs": [
      {
        "address": "0x0000000000000000000000000000000000001010",
        "topics": [
          "0xe6497e3ee548a3372136af2fcb0696db31fc6cf20260707645068bd3fe97f3c4",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x0000000000000000000000002ce910fbba65b454bbaf6a18c952a70f3bcd8299"
        ],
        "data": "0x0000000000000000000000000000000000000000000003a12d95cbbedbaf000000000000000000000000000000000000000000001cbfeb931a63433de7a508ff000000000000000000000000000000000000000000000035260b271eaddfeab300000000000000000000000000000000000000001cbfe7f1eccd777f0bf608ff0000000000000000000000000000000000000000000003d653a0f2dd898eeab3",
        "blockNumber": "0x2fc15e0",
        "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
        "transactionIndex": "0x0",
        "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
        "logIndex": "0xfffffffffffffffd",
        "removed": false
      },
      {
        "address": "0x0000000000000000000000000000000000001010",
        "topics": [
          "0x4e2ca0515ed1aef1395f66b5303bb5d6f1bf9d61a353fa53f73f8ac9973fa9f6",
          "0x0000000000000000000000007d1afa7b718fb893db30a3abc0cfc608aacfebb0",
          "0x0000000000000000000000002ce910fbba65b454bbaf6a18c952a70f3bcd8299"
        ],
        "data": "0x0000000000000000000000000000000000000000000003a12d95cbbedbaf0000000000000000000000000000000000000000000000000035260b271eaddfeab30000000000000000000000000000000000000000000003d653a0f2dd898eeab3",
        "blockNumber": "0x2fc15e0",
        "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
        "transactionIndex": "0x0",
        "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
        "logIndex": "0xfffffffffffffffe",
        "removed": false
      },
      {
        "address": "0xd9c7c4ed4b66858301d0cb28cc88bf655fe34861",
        "topics": [
          "0xec3afb067bce33c5a294470ec5b29e6759301cd3928550490c6d48816cdc2f5d",
          "0x0000000000000000000000007d1afa7b718fb893db30a3abc0cfc608aacfebb0",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x0000000000000000000000002ce910fbba65b454bbaf6a18c952a70f3bcd8299"
        ],
        "data": "0x0000000000000000000000000000000000000000000003a12d95cbbedbaf00000000000000000000000000000000000000000000000000000000000020109e41",
        "blockNumber": "0x2fc15e0",
        "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
        "transactionIndex": "0x0",
        "blockHash": "0x439632bd507fb885bb6d48de2cd7fd2c1fee06a8cd59359b70c358dfe25d0207",
        "logIndex": "0xffffffffffffffff",
        "removed": false
      }
    ],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000800100000000000008000000000000000080000000000000000000000000000000000000000800000000000000000000100000000000000000000000000000000000000000000000000000020000000000000010000000000000000000000040024000000000000000000000204000000000000000000000000000000000000000000000000000000000000000000000000000000004000000020000002000000000000000000000000000000800000108000000000000000000000002010000000000000000000000000000000080000000000100002",
    "status": "0x1",
    "to": "0x0000000000000000000000000000000000000000",
    "transactionHash": "0x6629e2405a8f056e026d78ce91ee0f56a8eb9f02f0c83093e817cca32ffbecdb",
    "transactionIndex": "0x0",
    "type": "0x0"
  }
}
```

**Comment by sudeepdino008** [comment]
should be fixed in 3.1.0 release
the issue in 3.0.15 is known. As you figured out, it was fixed in 3.1.0-rc (except the wrong logIndex, which'll be fixed in 3.1.0)

**Comment by MightyMercurian** [comment]
This issue seems to still present in Erigon 3.1.0 on Polygon Amoy testnet for blocks beyond the prune distance.

## Our Findings:

**Test Setup:**
  - Erigon 3.1.0
  - Polygon Amoy testnet
  - Queried transaction: `0xf2a1912cea678411257851aa50e6e5df7fe8b5c2402a13ca85003c60be82a27d ` (block 26281492)

**Results:**
When querying the same transaction receipt:
  - **Our Erigon node (pruned)**: Returns `logIndex: 0xffffffff` (4294967295)
  - **Public RPC (polygon-amoy.drpc.org)**: Returns `logIndex: 0x1` (correct value)
  - **Other public RPCs**: Also return correct values

**Pattern Observed:**
  - Recent blocks (within ~300k prune distance): Work correctly
  - Old blocks (beyond prune distance): Return 0xffffffff due to the unsigned integer underflow
  - This causes JSON parsing failures in clients expecting valid 32-bit integers

**Comment by VBulikov** [comment]
yperbasis added Imp3 as Importance

**Comment by AskAlexSharov** [comment]
unfortunately we unlikely will start work on this task in near future. Polygon has own Erigon fork. pls report there. sorry. thank you for reporting.

**Comment by yperbasis** [comment]
(Here's the fork repo: https://github.com/0xPolygon/erigon)
