### ISSUE TITLE
Issue with streaming queries inside batch

### ISSUE THREAD

**Issue by romankoblov** [ledgerwatch/erigon#2210]
#### System information

Erigon version: erigon version 2021.06.4-alpha
OS & Version: Linux
Commit hash : -

#### Expected behaviour
Streaming queries works correctly in batch json rpc request.

#### Actual behaviour
Streaming query (trace_filter for example) inside batch request breaks response of that request:

```
{"jsonrpc":"2.0","id":1,"result":[{"action":{"from":"0xf2972a2b8eda253678877995147869ed99b50e39","callType":"call","gas":"0x8fc","input":"0x","to":"0x3ecef08d0e2dad803847e052249bb4f8bff2d5bb","value":"0x295fdffa482759"},"blockHash":"0x99f477bb23969a0dbf37aac81e0cc916d90368b456517cf960adccd4314bf60d","blockNumber":12668429,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[4],"transactionHash":"0x41e879723286921ffb2f526f73230ce582a8e06b3f3edd8fcfcd95f25f53467d","transactionPosition":2,"type":"call"},{"action":{"from":"0x3ecef08d0e2dad803847e052249bb4f8bff2d5bb","callType":"call","gas":"0x13498","input":"0x","to":"0x18a96ed106263ebc3664235e070535c379c49493","value":"0x5e138be50cb9c00"},"blockHash":"0x99f477bb23969a0dbf37aac81e0cc916d90368b456517cf960adccd4314bf60d","blockNumber":12668429,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x68671aa17b7bc5d38a429ad1e4224e252efc1f4388477c88b520637e5e9d153a","transactionPosition":3,"type":"call"},{"action":{"from":"0x3ecef08d0e2dad803847e052249bb4f8bff2d5bb","callType":"call","gas":"0x13498","input":"0x","to":"0x4be09cf857c6031c5788a37788404682c84f33a0","value":"0x2d77a7718896000"},"blockHash":"0x99f477bb23969a0dbf37aac81e0cc916d90368b456517cf960adccd4314bf60d","blockNumber":12668429,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0xa396b87478eac8422bb85be35f36ca028ed079f624d4d2d0ed53b91477d68a7a","transactionPosition":4,"type":"call"},{"action":{"author":"0x3ecef08d0e2dad803847e052249bb4f8bff2d5bb","rewardType":"block","value":"0x1bc16d674ec80000"},"blockHash":"0x99f477bb23969a0dbf37aac81e0cc916d90368b456517cf960adccd4314bf60d","blockNumber":12668429,"result":null,"subtraces":0,"traceAddress":[],"transactionHash":null,"transactionPosition":null,"type":"reward"},{"action":{"author":"0x3ecef08d0e2dad803847e052249bb4f8bff2d5bb","rewardType":"block","value":"0x1bc16d674ec80000"},"blockHash":"0x244fb683edae67a2050b7a1214885c6b721b28ea47f014555aec7e718eb2a35d","blockNumber":12668452,"result":null,"subtraces":0,"traceAddress":[],"transactionHash":null,"transactionPosition":null,"type":"reward"}]}
[{"jsonrpc":"2.0","id":0,"result":"0xc14e52"}]
```
As you can see response for 'trace_filter' is outside of batch response array and even more, there is two json responses separated by line break which doesn't make sense in case of http query. 

#### Steps to reproduce the behaviour
```
curl http://127.0.0.1:8545 -X POST -H 'Content-Type: application/json' --data '[{"method":"trace_filter","params":[{"fromBlock":"0xc14e0d","toAddress":["0x3EcEf08D0e2DaD803847E052249bb4F8bFf2D5bB"],"fromAddress":["0x3EcEf08D0e2DaD803847E052249bb4F8bFf2D5bB"],"after":0,"count":1000}],"id":1,"jsonrpc":"2.0"}, {"method":"eth_blockNumber","params":[],"id":0,"jsonrpc":"2.0"}]'
```

**Comment by AskAlexSharov** [comment]
@romankoblov , hi. I think we fixed this issue - feel free to test it on last devel branch

**Comment by romankoblov** [comment]
> @romankoblov , hi. I think we fixed this issue - feel free to test it on last devel branch

Sorry for late response, I've re-synced node. Unfortunately bug is still here, request from issue returns:
```{"jsonrpc":"2.0","id":1,"result":[...<300kb>...:"reward"}null,"error":{"code":-32000,"message":"failed ReadCanonicalHash: EOF, number=12672159"}}
[{"jsonrpc":"2.0","id":0,"result":"0xc3a528"}]``` at commit b6b42930add51105da11e387222357cf820b6f73

**Comment by Uxio0** [comment]
Same bug is going on for us, example trace:

```
{"jsonrpc":"2.0","id":1058,"result":[{"action":{"from":"0xdb5dfe548e79441e709edd46f21d80cbd245b1be","callType":"delegatecall","gas":"0x5473a","input":"0x468721a7000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c5497000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008459f96ae50000000000000000000000006810e776880c02933d47db1b9fc05908e5386b96000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000000000000000000000ce00000000000000000000000000000000000000000000000260fc236dafffdae800000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0xe54d9e68fa35afbdf4d07930f544d651d87bb77e45c44e438a3d2b7a6925f0c8","blockNumber":7806645,"result":{"gasUsed":"0x24445","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0x4431fe6ea1c2e6f51dc605569bc5e5fcfa35a2ae3e742370fb5d13f5f50602a0","transactionPosition":32,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0x4ea8891422569be3ed62a2c91ba9ac0208f6d41808dd5befdfd55a4644c3e26a","blockNumber":7806646,"result":{"gasUsed":"0x617f","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0x542b1474c96767b1b0781deeb1a5065a2cf36268c460c468f6f805fe4f427178","transactionPosition":52,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0x45783a40f53d85e641ddfab1ae8564b5b0f326b603cbd1684c815d45aa4e863d","blockNumber":7806648,"result":{"gasUsed":"0xb55","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0x24845423feee0be6ae91b58209fc643121d105b46934387b5e3ed87eb560a3ff","transactionPosition":41,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0xdecfdc2608577d6359d8bf51da2be1e9b10d373a550a3f21a0e0feb0c9c2b662","blockNumber":7806649,"result":{"gasUsed":"0xb55","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0xec1ad7c8a0dcf0b6705d7ed3b8931484716383d8da0acf70a3b94866c8ab15e2","transactionPosition":24,"type":"call"},{"action":{"from":"0x2f41a93b59acb94ca8cfd91178a2a537aed02bed","callType":"delegatecall","gas":"0x22891","input":"0x468721a7000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c549700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a47895dd21000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000002f41a93b59acb94ca8cfd91178a2a537aed02bed0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000255aa6df07540cb5d3d297f0d0d4d84cb52bc8e60000000000000000000000000000000000000000000000000000000000000002000000000000000000000000255aa6df07540cb5d3d297f0d0d4d84cb52bc8e6000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000179000000000000000000000000000000000000000000000000000000000000017900000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0x8699fffac845f900e16b9871741303ac4cfbb7855b81ecbe755df179a59cad93","blockNumber":7806650,"result":{"gasUsed":"0x9f66","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0xc65d444255cbaace49f57d7be9fc1f5915ef39542a7e9307c9b4562b14659e18","transactionPosition":63,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0x24d4be9ad85a76ca9d6529365088d782f8df05740baa00c8858e0d46dfa0a04e","blockNumber":7806651,"result":{"gasUsed":"0xb55","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0xe6105b577b87962f6cf28288798bae1103667d24e33bde90c6d1ea58dbeb64ed","transactionPosition":99,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0xbb2668c741c21c35a49ea772cb721086ecc6348473773ccfcab46e6edf5d8de5","blockNumber":7806654,"result":{"gasUsed":"0xb55","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0xe94f2e6e4c143e5415bab4f316f09b1b2ef34763234eb0f4f0d10d3efce4f003","transactionPosition":23,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0x22624275cb0638aede2c5b6c5626984e60f5ac17e1f69bff1c3cab6ab7509bf8","blockNumber":7806656,"result":{"gasUsed":"0xb55","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0x8e6bf649fb7e3da7f04667348cc91cd12f8d3f07c1303bb224b603da9fdd236e","transactionPosition":71,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0x22624275cb0638aede2c5b6c5626984e60f5ac17e1f69bff1c3cab6ab7509bf8","blockNumber":7806656,"result":{"gasUsed":"0xb55","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0xb940a19860efda34892ae7c43bc87e5fd93729c698b5a453b5f779688c9e5991","transactionPosition":72,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0xb9c9c3b21acb8332f2109bfd0bfb59ca09c6724497b028e5c2fc940c03bd2514","blockNumber":7806659,"result":{"gasUsed":"0xb55","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0x19160b8675757a108dc1834222aa520dae9b5b523a348c7ed50485c771ef8218","transactionPosition":18,"type":"call"},{"action":{"from":"0x9a6dd72f073e66ab5b1890e1643771669ab08ed1","callType":"delegatecall","gas":"0xb164","input":"0x468721a7000000000000000000000000d26114cd6ee289accf82350c8d8487fedb8a0c070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000b9812e2fa995ec53b5b6df34d21f9304762c54970000000000000000000000000000000000000000000000d8d726b7177a80000000000000000000000000000000000000000000000000000000000000","to":"0x8942595a2dc5181df0465af0d7be08c8f23c93af","value":"0x0"},"blockHash":"0x6adb0814eed10d0fe7e678b08cf720bb6b2615adf88da16045d033202faaea8b","blockNumber":7806660,"result":{"gasUsed":"0xb55","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[0,0,0],"transactionHash":"0xc73f31a18568c5816275abb3855d0a832ec1e94c22c4a6c4eaae1fc2cf467196","transactionPosition":78,"type":"call"}null,"error":{"code":-32000,"message":"failed ReadCanonicalHash: EOF, number=7806662"}}\n' because of Expecting ',' delimiter: line 1 column 12711 (char 12710).: line 1 column 12711 (char 12710)
```

**Comment by AskAlexSharov** [comment]
Right now if batch does have "streamable" request - will execute in 1 goroutine (no parallelizm).
And I wonder - maybe just prohibit "streamable" requests in batch at all? (instead of fixing this issue). 
Because batching of such requests will only slow-down overall response time.
@AlexeyAkhunov - how do you think?

**Comment by romankoblov** [comment]
> Right now if batch does have "streamable" request - will execute in 1 goroutine (no parallelizm).
> And I wonder - maybe just prohibit "streamable" requests in batch at all? (instead of fixing this issue).

Please don’t. Better leave as is, it is not hard to parse (almost same as tcp jsonrpc). 

> Because batching of such requests will only slow-down overall response time.

Even in current state with 1 goroutine per request it has same speed as multiple requests, because there is significant overhead for creating new connections (especially https one). Also, there is limit in browser for something around 6 parallel connections which slow-down non-batched requests. 

Why not just create in-memory stream in goroutine for each streamable request and then just concat bytes with current response at the end? That way it can be easily parallelized. Memory usage will be slightly higher than with multiple requests (but not always, there is tcp buffers for each open socket anyway). Request from issue takes 1.5 min to return 500kb, so for big requests it is worth to split them by some block range anyway.

**Comment by romankoblov** [comment]
BTW, if problem with https://github.com/ledgerwatch/erigon/blob/360735318b53a9b8ad2f97b048bf139da0ec6cf5/rpc/handler.go#L147 

It is not neccessary per jsonrpc spec (https://www.jsonrpc.org/specification): 
> The Server MAY process a batch rpc call as a set of concurrent tasks, processing them in any order and with any width of parallelism.

>The Response objects being returned from a batch call MAY be returned in any order within the Array. The Client SHOULD match contexts between the set of Request objects and the resulting set of Response objects based on the id member within each Object.

There is 'id' field inside each request/response which should match, but order can random.

**Comment by AskAlexSharov** [comment]
@romankoblov , problem that "streaming" writing to client for long time - and there is no intermediate buffer - because some requests do eat all memory if use intermediate buffer. It means can send anything to client while 1 "streaming" does sending.

`streamable` - means - send data to client before request is finished. "concat in the end" - means make request non-streamable. 

To give more contest - some requests (like trace_blockTransactions, etc...) - may eat all RAM :-)
Problem is - you don't really know - will response big or small until you get it. And make decision "run in parallel or not" need in advance.

About - making this response valid - it's probably doable.

**Comment by AskAlexSharov** [comment]
I have idea to de-optimize streamable requests for batch and ws. To use in-mem buffer. 
For ws - looks very hard to implement due to too many abstractions there.
For batch - i didn't check, probably doable.

**Comment by AskAlexSharov** [comment]
@romankoblov , hi. can you help me to test https://github.com/ledgerwatch/erigon/pull/2377

**Comment by romankoblov** [comment]
> @romankoblov , problem that "streaming" writing to client for long time - and there is no intermediate buffer - because some requests do eat all memory if use intermediate buffer. It means can send anything to client while 1 "streaming" does sending.

> `streamable` - means - send data to client before request is finished. "concat in the end" - means make request non-streamable.

You can stream batch responses (when they any of them got result), but streaming queries will require intemediate buffer. 

> To give more contest - some requests (like trace_blockTransactions, etc...) - may eat all RAM :-)
> Problem is - you don't really know - will response big or small until you get it. And make decision "run in parallel or not" need in advance.
> 

For streaming queries if DDoS via big queries is really concern, you can limit response inside handlers by checking internal buffer len of stream and stop processing request after some limit. For tracing API its probably worth checking that all responses from same block is processed since API doesn't allow any other way to paginate.

> @romankoblov , hi. can you help me to test #2377
Sure, I've actually just did PR with same changes, we even select same buffer length :) But my PR also fixes websockets. Maybe better to use it?

**Comment by AskAlexSharov** [comment]
I think we are done here. Closing. Feel free to re-open.

**Comment by Uxio0** [comment]
Hi @AskAlexSharov, we are currently using https://github.com/ledgerwatch/erigon/releases/tag/v2021.07.04 and we still see the same issues. We are still getting this from time to time when using `trace_filter`:

```json
{"jsonrpc":"2.0","id":4132,"result":[{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a7f8","input":"0xd4d9bdcdf78d3a53c51eacb4b6685c6dc0399c862263ac01b757b76b5c0958b9f5967b03","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x63e0ba96e0bb81f2b7e922c66b8b6829c6edf0cc6125486bd6c42cd941b38da5","blockNumber":10365147,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x60922569d9823c1a0953f5e042bc4ae968480606efaba5f402d553132eb78450","transactionPosition":6,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a7f8","input":"0xd4d9bdcdc7fdb69ff2b312dff77b8ec903f33af868d2dbe502eb53073550212d231df6c0","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0xeb59f69b57286c80e9a8dbfbfd5f0d5c9bf80fe709306b0b2578e2cf4c81a4e3","blockNumber":10365149,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0xc63b9a90bffc7a14572ab4fe286014fe0c3abd76a8bb0748e5af0500b749bc7e","transactionPosition":27,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x27af8","input":"0x6a761202000000000000000000000000ae38b81459d74a8c16eaa968c792207603d844800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000243be99e6f00000000000000000000000061166014e3f04e40c953fe4eab9d9e40863c83ae0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001454f3c749c70f3866d8dc6295197c700aef7756726a40409c618bca822c120220b59db9d0fc1e037c90323beb0091877a48ae027f5b259f1296fc92e743b1de2bf1fe8c2404869322e23ef6e2f8c9a401b57b15eb68b3970b96fd1a971c13af7947e613c8976ac99b2a0e5f1a7027e5925a6f96383f91ffd86ece8a41b8b020016f2204b7cdf8a507025a2a788d6980b201cdef05e8d300f485856e2d72691246dca98432b6ad6dc9e4c15e6555bbe9e176c20eb6deba4990285b715e32fd78f9e352b1f000000000000000000000000d7e5c7ec37cde3f42597a5018e9320070c288b82000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de910777c787903f78c89e7a0bf7f4c435cbb1fe000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0xeb59f69b57286c80e9a8dbfbfd5f0d5c9bf80fe709306b0b2578e2cf4c81a4e3","blockNumber":10365149,"result":{"gasUsed":"0x18199","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0],"transactionHash":"0xd6ae833b22f5d77f9b94d3df872e7be877d88f2017981a351e9258dac7b013d8","transactionPosition":72,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a7f8","input":"0xd4d9bdcda812b58ff748cf4e0f4188a7cd82d90233add4c3e7885afc01412c6976708a57","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x0256c9aa70e0a792c39f7cb3db197665d2c64b25f4bdcc14d15749b409b51d5f","blockNumber":10365151,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x65c30c20236f7a46edb745bea4aa8ec043dba332ac3f0df0349f824690a887d1","transactionPosition":88,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x27b04","input":"0x6a761202000000000000000000000000e04d8770dc06135dd97214ea8bcbf7b1cc057aa30000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000243be99e6f00000000000000000000000061166014e3f04e40c953fe4eab9d9e40863c83ae000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000145788f1fa3e947da89a6cec41cdcb5c637674bda0e4ca058f028f541d023d0b22a08586eefc02da0d8980699b927d5019f20c7db54c2daea11345f847ee671526e20e6e863ea7e1c6ee66861b05272adb8482f91c598be439efd95573e8081558d472b24ae54ae96e5a0870644849c270e10c8c5d86859caa4774e8dbac7555ba3c41fd17ab3791546a2cfd5834a8771641ce881984046edc852dd38707e20473faa8646f9f50f1beec6f24df5a6377d9557c859de45764283df33da7c13951561692e20000000000000000000000000d7e5c7ec37cde3f42597a5018e9320070c288b82000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de910777c787903f78c89e7a0bf7f4c435cbb1fe000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x0256c9aa70e0a792c39f7cb3db197665d2c64b25f4bdcc14d15749b409b51d5f","blockNumber":10365151,"result":{"gasUsed":"0x18199","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0],"transactionHash":"0x38eb699e50d2d2f7f9f9802f893d6fea9bf4192e9f43c4e0228f9ffe43e1284b","transactionPosition":174,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a7f8","input":"0xd4d9bdcd2a1a7fce1694ef95b1878cf76c7ad7a4e7f30ccf19743c925b6071be3c8dae5f","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0xb91784daec2a33af3b7b9108317bad54c3d5170422083d7f9fe23b767ed0df4f","blockNumber":10365154,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0xdddde28d508c24d2117bbc2709fdac73779ae08657ed94070c68006084f1c911","transactionPosition":25,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a7f8","input":"0xd4d9bdcd73827d01df056735dd7f9e94f5817235e497dc5f539a42e03a37971931476fe5","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x3bd87c062f2a729d3b22f48c9d8dd822e8962f4b8131b6afd6565c04da293c51","blockNumber":10365156,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x217cea30ec03e150bada7f5fda7cc3f525b7108c833c25f45d39592f59109fa5","transactionPosition":69,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x27b04","input":"0x6a761202000000000000000000000000b3098ae40f488ffdb979827fd01597cc20c5a5a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000243be99e6f00000000000000000000000061166014e3f04e40c953fe4eab9d9e40863c83ae00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014515f3ce9da1447de65b541f9b9b4eebde103f131a991e8e9e51fd19c55050f5ef0d8d4b4954079879037d7ab04c95dd302226a61eb3076f230e85ec36c5db15c620cac570fa30ce2c2874d32b77519d36516895a608e2e818ace2b315e22f4a606219c69af89448195e01243a6332ae53a40c1294cf60011097464d35943358dcd21f75fdeae9ead4eeb6db10fa64215fbb1e1592aea63a02b49ca18babbae134dd865328b650638cd2aad54147bcf7d266383bd6deb9c06936a268bce883dade916020000000000000000000000000d7e5c7ec37cde3f42597a5018e9320070c288b82000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de910777c787903f78c89e7a0bf7f4c435cbb1fe000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x3bd87c062f2a729d3b22f48c9d8dd822e8962f4b8131b6afd6565c04da293c51","blockNumber":10365156,"result":{"gasUsed":"0x18199","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0],"transactionHash":"0xfba7edc459fdce6db94909b74df79bf17c432cdca2bf13e56d76d25d2e910a9b","transactionPosition":145,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a7f8","input":"0xd4d9bdcd9c258d22c6462483c695f71df5c468022226c38489c2c197f74352d5af75d94c","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x6aebbdc5b9d5fc1ec1b6f5f59f9820e46cee5ee3cac6b01e985fa3b7521501d3","blockNumber":10365158,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x40402d72bf94fdf9ead899c9d0ce521f54eda7fdbd18f50096d6b9900ea17f01","transactionPosition":59,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a7f8","input":"0xd4d9bdcd313e870ec7e98ff195dea1bdfff8d40e41ca1653f71d4e12e1356783103f312a","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x85db4934d83d227ef03fdaeff5fba1a82aadf7fd60736cd93652d363b221ba8c","blockNumber":10365160,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x2025edc2bd5e960e87a4008305ac53c4e3d340d266505b854fffdacf1a85df6e","transactionPosition":13,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x27b04","input":"0x6a761202000000000000000000000000253914cf059f4c3e277c28060c404acfc38fb6e20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000243be99e6f00000000000000000000000061166014e3f04e40c953fe4eab9d9e40863c83ae000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000145134c26e673e8d9244d0744b7679290644ef48f669e8bc83332e947a3ab5aa053377d119cbb3d51fa182937da5e02d3b3654a48ad94d4edd32c88e88b234df54e1f4cc45c82ce2b64dc23fb3190892bce7a642ff4b9e523da5e3587b99481892dd71e1916bd95b548b6f36f3d3d34340e358a07a5347685eb513af77ce1199c2b6820ff4af708a129daafb243324e50c48904f2e6a658e34f24661c64056803738e5b174c67affc5573f0db679d5f7d4490e9f9d49e9cf57bfadb3676c6942a29f48b1f000000000000000000000000d7e5c7ec37cde3f42597a5018e9320070c288b82000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de910777c787903f78c89e7a0bf7f4c435cbb1fe000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x85db4934d83d227ef03fdaeff5fba1a82aadf7fd60736cd93652d363b221ba8c","blockNumber":10365160,"result":{"gasUsed":"0x18199","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0],"transactionHash":"0x62fe50a46996c3ef0a195bac3e7678ca089a6b7df67b16f8bff4f7104d8362e6","transactionPosition":20,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a7f8","input":"0xd4d9bdcd8f59ca848d7fdccf8a2e73641e308523eacf46b71dd8b63f627755723482cb51","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x03ac9af8ded9d70190760d21306116e01f5c611bf60fc86d5c54bf18bbee87c7","blockNumber":10365162,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x96c44c209db907c7ff3427b783d5044da14d0a1f9f58985a09da52e17f91caac","transactionPosition":191,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x27afe","input":"0x6a761202000000000000000000000000a408d8e01c8e084b67559226c5b55d6f0b7074e20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000243be99e6f00000000000000000000000061166014e3f04e40c953fe4eab9d9e40863c83ae00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014597ecac017da883bff11dfa297ca4da8c49110ecda6726b62bfa83f426a4d922d1ad126cb81bc300395ece6f1a592d5057b7da8b74d46c30537b30a5874462b432073d0ff0fb35d579be582cb1cb0c4523990a75d2c2c2c74a900f89fe447f2b4a510abe46d5b7a465bf77629a79db40e0adaea0beb4be1706c08f7a778b871c69920dd76e55093de534f72c954c319f8d178627e4ead0b8e93481b18b0614bf31d9e510f7872c1e34d6e8ce58fbc868d4ecd6bb9d59422741ce9d508b21bbe2f803020000000000000000000000000d7e5c7ec37cde3f42597a5018e9320070c288b82000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de910777c787903f78c89e7a0bf7f4c435cbb1fe000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0xcb3b22581d120f10b5b12de4c847d55531f72fca3629bda8a31af4a1b4675378","blockNumber":10365163,"result":{"gasUsed":"0x18199","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0],"transactionHash":"0x341afe80575f934690998bf58db180e1bb6cf51593d10436db7d784e6fc75437","transactionPosition":245,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x27afe","input":"0x6a761202000000000000000000000000a408d8e01c8e084b67559226c5b55d6f0b7074e20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000243be99e6f00000000000000000000000061166014e3f04e40c953fe4eab9d9e40863c83ae00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014597ecac017da883bff11dfa297ca4da8c49110ecda6726b62bfa83f426a4d922d1ad126cb81bc300395ece6f1a592d5057b7da8b74d46c30537b30a5874462b432073d0ff0fb35d579be582cb1cb0c4523990a75d2c2c2c74a900f89fe447f2b4a510abe46d5b7a465bf77629a79db40e0adaea0beb4be1706c08f7a778b871c69920dd76e55093de534f72c954c319f8d178627e4ead0b8e93481b18b0614bf31d9e510f7872c1e34d6e8ce58fbc868d4ecd6bb9d59422741ce9d508b21bbe2f803020000000000000000000000000d7e5c7ec37cde3f42597a5018e9320070c288b82000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de910777c787903f78c89e7a0bf7f4c435cbb1fe000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0xcb3b22581d120f10b5b12de4c847d55531f72fca3629bda8a31af4a1b4675378","blockNumber":10365163,"error":"Reverted","result":null,"subtraces":0,"traceAddress":[0],"transactionHash":"0x5ead1a3d817d0d723d938d083b574bd4386600fee01386c92f79196e51be2e9b","transactionPosition":246,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x2a804","input":"0xd4d9bdcd2b7dd79132014f0d11a4e1cf99002d9d40b45a44f777fd7e7dc21a4f6aa9e023","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x254eae5d5a9d37597a8fef00bd247033b47c0d736d637e87c927993f8014af9e","blockNumber":10365164,"result":{"gasUsed":"0x59d7","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0xd9fdb27d2834987ea04fa26ec121beb4ab1efec69f552ff431d3cdc9e0fdd11d","transactionPosition":70,"type":"call"},{"action":{"from":"0xeb3107117fead7de89cd14d463d340a2e6917769","callType":"delegatecall","gas":"0x27b04","input":"0x6a7612020000000000000000000000001b9d6cd65ddc981410cb93af91b097667e0bc7ee0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000243be99e6f00000000000000000000000061166014e3f04e40c953fe4eab9d9e40863c83ae000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000145ead8a13f968dd23fc73e3e8ff9e65177efa3b329c58fcda302bd7bedd1ff88bb331d525ea764087676e20d2b193f2fcc51392c19fcd81a389975b265ab8e67ea1f613c540e99a85760eb785d07bf0a24c151e0c827354a2d60d670b8142a4a85355e2f3a10b796ee63a7527197d9b2935649a2e14dbf11b6017c247051ffa4a0521f6a04dff09cd342ce5005ce5a9521bfe2da507c215e4278bce3b6d6d29bc89a27173adadd24e7219a8072716637d7f6d4f4e8f18f128944a453cdad1a8ebbb58420000000000000000000000000d7e5c7ec37cde3f42597a5018e9320070c288b82000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de910777c787903f78c89e7a0bf7f4c435cbb1fe000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000","to":"0x34cfac646f301356faa8b21e94227e3583fe3f5f","value":"0x0"},"blockHash":"0x8674efb7ace9ca2ecc69714384e88e657d59da41ee0b6472c1c1c23b16d00047","blockNumber":10365165,"result":{"gasUsed":"0x18199","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0],"transactionHash":"0xd649e0d26bd3862562c8910bff1783395c6f28cfcfdef387ff1cedab1d3c8f02","transactionPosition":120,"type":"call"}null,"error":{"code":-32000,"message":"failed ReadCanonicalHash: EOF, number=10365169"}}\n' because of Expecting ',' delimiter: line 1 column 20181 (char 20180).: line 1 column 20181 (char 20180)
```

**Comment by AskAlexSharov** [comment]
@Uxio0 , thank. i will take a look. do you use HTTP or WebSocket?

**Comment by Uxio0** [comment]
Hi, just HTTP. Thanks for the quick response

**Comment by AskAlexSharov** [comment]
Here is the fix: https://github.com/ledgerwatch/erigon/pull/2464
