### ISSUE TITLE
eth_getBlockByNumber returns null for pending block

### ISSUE THREAD

**Issue by shark0der** [ledgerwatch/erigon#2771]
I'm trying to get the baseFee of the pending block to avoid usage of gas price oracles. Requesting pending block information returns null, however the same request works well against geth.

#### System information

Erigon version: `erigon version 2021.10.1-alpha`

OS & Version: Ubuntu 20.04.3 LTS

Commit hash : `ef80fd54b1c6c82aae92f5fa24cbd381e8577b50`

#### Expected behaviour
`"method":"eth_getBlockByNumber", "params":["pending", false]` should return the pending block information.

#### Actual behaviour
```
curl -sq http://IP:8545 -H 'Content-Type: application/json' \
  --data-raw '{"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending", false]}'
{"jsonrpc":"2.0","id":1,"result":null}
```

#### Steps to reproduce the behaviour
Running erigon with the following config:

`erigon --datadir /data/erigon --prune=htc --private.api.addr 127.0.0.1:9090`
`rpcdaemon --http.api web3,eth,debug,net --http.addr <IP> --http.vhosts '*' --http.corsdomain='*' --ws --verbosity 3`

#### Backtrace
No backtrace as there's no crash.

**Comment by AndreaLanfranchi** [comment]
Actually the method will return something only if `--mine` command line argument is enabled in Erigon cause otherwise Stage 5 [MiningCreateBlock] is not invoked and no "pending" block exists.

This said the reponse however lacks at least basefee (post EIP-1559). Keep issue opened for reference

**Comment by AskAlexSharov** [comment]
FYI: I added baseFee to miner https://github.com/ledgerwatch/erigon/pull/2773

will think about pending block

**Comment by mohoff** [comment]
Do anyone know if this is fixed in a more recent release?

**Comment by AskAlexSharov** [comment]
I think - no.

**Comment by mandrigin** [comment]
@yperbasis @Giulio2002 will this be fixed in the current alpha? because we prepare the block for validation, right?

**Comment by yperbasis** [comment]
It is probably not fixed yet: we need to wire one (the most recent?) of `EthBackendServer.builders.block` (PoS blocks being assembled) as the pending block into `eth_getBlockByNumber`.

**Comment by dmitriyselivanov** [comment]
I will take this one if nobody is working on it already.

**Comment by nebojsa94** [comment]
Just tried this on version `08.03-alpha`, but I'm always getting `no pending block found returning latest executed block`
