### ISSUE TITLE
New pending transactions streaming subscribtions are very slow

### ISSUE THREAD

**Issue by Sleapy31** [ledgerwatch/erigon#3373]
#### System information
CPU : AMD 5950x
Drives : 3.2TB NVME
RAM : 128Go

Erigon version: `./erigon --version`
erigon version 2022.99.99-dev

OS & Version: Windows/Linux/OSX
Ubuntu 20.04

Commit hash : 

#### Expected behaviour
Having a stream of new pending transactions in "real time" when they reach the node.

#### Actual behaviour
I receive new transactions at a very slow speed, like 8tx/s. (3-4tx/s if I also run my program logic).
Also, I have 2/32 threads that run at 100% and others at 0% so I'm bottleneck and no other threads are used. 
I don't know if it's because websocket and http are on the same port by default (8545) and then the rpcdaemon can't handle to receive data from websocket while calling the node to fetch more data.

#### Steps to reproduce the behaviour
Launch erigon and rpcdaemon with ws support, then with your favorite web3 client, subscribe to newPendingTransactions stream and write in the console every changes (every new transaction hash) and estimate the speed.

#### Comments:

I have no issues with Geth, I had some with OpenEthereum who was slower for streaming newPendingTransactions, Erigon is the slowest. What can I do to improve the speed ?

**Comment by AskAlexSharov** [comment]
Thank. I understand the reason. Will fix soon.

**Comment by Sleapy31** [comment]
> Thank. I understand the reason. Will fix soon.

Hi, thank you very much.
what is the exact reason please ? For educational purpose

**Comment by AskAlexSharov** [comment]
TxPool does send sequentially notifications about new txs to rpcdaemon and to p2p peers, but p2p peers are slow.
It was done by intention - for simplicity - we trying introduce goroutines only when really need. But of course 1 slow peer must not affect speed of other peers notification or API client notification.

**Comment by Sleapy31** [comment]
Ok I understand now, thank you.

**Comment by AskAlexSharov** [comment]
Fixed by https://github.com/ledgerwatch/erigon/pull/3452

**Comment by Sleapy31** [comment]
Hi, I have tried devel branch and last released branch and it is still the same or worse.

**Comment by erthink** [comment]
@AskAlexSharov or @AskAlexSharov, please confirm that this issue is not related to libmdbx or vice versa.

**Comment by Sleapy31** [comment]
So, I get new events very slowly, initially I thought it was because Erigon Txpool was filtering it to only receive new tx and not old one as geth does by default.
But when I do some testing (launch the subscribtion and listen to my address who send a tx, then wait several minutes or hours and send a tx with a public and/or private RPC endpoint) sometimes I get the tx and sometimes I don't. 
When I try this for geth I always get it.

So maybe I receive all the new transactions hash as expected but my node is not connected to enough peers ?
I'll try different parameters and let you know.

**Comment by rangerf** [comment]
Hi Sleapy31 

> So, I get new events very slowly, initially I thought it was because Erigon Txpool was filtering it to only receive new tx and not old one as geth does by default. But when I do some testing (launch the subscribtion and listen to my address who send a tx, then wait several minutes or hours and send a tx with a public and/or private RPC endpoint) sometimes I get the tx and sometimes I don't. When I try this for geth I always get it.
> 
> So maybe I receive all the new transactions hash as expected but my node is not connected to enough peers ? I'll try different parameters and let you know.

Hi Sleapy did you managed to fix this ? I am testing 2 nodes one with 2022.05.04 commit and another with 2022.06.01 and still same thing for me if I am trying to back run specific transaction and it actually hears the transaction all is good but the main problem is that most of the time it doesn't hear the transaction I am looking for

**Comment by AskAlexSharov** [comment]
ok, need investigation, let's go to  https://github.com/ledgerwatch/erigon/issues/3892

**Comment by Sleapy31** [comment]
> Hi Sleapy31
> 
> > So, I get new events very slowly, initially I thought it was because Erigon Txpool was filtering it to only receive new tx and not old one as geth does by default. But when I do some testing (launch the subscribtion and listen to my address who send a tx, then wait several minutes or hours and send a tx with a public and/or private RPC endpoint) sometimes I get the tx and sometimes I don't. When I try this for geth I always get it.
> > So maybe I receive all the new transactions hash as expected but my node is not connected to enough peers ? I'll try different parameters and let you know.
> 
> Hi Sleapy did you managed to fix this ? I am testing 2 nodes one with 2022.05.04 commit and another with 2022.06.01 and still same thing for me if I am trying to back run specific transaction and it actually hears the transaction all is good but the main problem is that most of the time it doesn't hear the transaction I am looking for

No I haven't solve it yet. In fact I stopped using Erigon because of this issue.
I am glad that I am not alone and someone finally hear us lol.

**Comment by MycoinTool** [comment]
same issue, It's so torturous.
Want to stop using Erigon too.
