### ISSUE TITLE
Stuck at `Wrote block headers..`

### ISSUE THREAD

**Issue by vanphandinh** [ledgerwatch/erigon#4081]
#### System information

Erigon version: `erigon version 2022.99.99-dev-77441916` -- I just pulled and built the latest version 2020.05.02

OS & Version: Ubuntu 20.04.3 LTS

Commit hash : git_branch=devel git_tag=v2022.05.02 git_commit=77441916fd32957c7e40474559ffb204bbceff92

#### Expected behavior

Syncing finished.

#### Actual behaviour

Stuck at `Wrote block headers       number=14648991 blk/second=0.000 alloc=6.9Gb sys=20.3Gb`

#### Steps to reproduce the behavior

`/root/erigon/build/bin/erigon --datadir=/root/erigon-data/ --torrent.download.rate=512mb --prune.h.before=12525700 --prune.r.before=12525700 --prune.t.before=12525700 --prune.c.before=12525700 --private.api.addr=localhost:9090`

I've tried to restart Erigon, but it produced the same logs
I also tried to follow this guide: https://github.com/ledgerwatch/erigon/issues/3964#issuecomment-1114130777 but it doesn't work

#### Backtrace

![Screen Shot 2022-05-05 at 1 01 30 PM](https://user-images.githubusercontent.com/13887599/166870657-1f71c6fd-6f7a-4e18-88d3-3a30a7093ad3.png)

**Comment by AskAlexSharov** [comment]
Fixed by https://github.com/ledgerwatch/erigon/pull/4078

**Comment by vanphandinh** [comment]
> Fixed by #4078

I just ran git pull & built erigon from the latest version 1-2 hours ago
Are you sure the bug is fixed?
I am still facing it :|

**Comment by AskAlexSharov** [comment]
I just know that author of https://github.com/ledgerwatch/erigon/pull/4078 told that without this fix we can get "infinity loop". 
maybe your problem is somewhat different.

**Comment by AskAlexSharov** [comment]
- Erigon restart - didn't help?

**Comment by vanphandinh** [comment]
> * Erigon restart - didn't help?

yes, I restarted many times, it produced the same problem at the end

**Comment by vanphandinh** [comment]
`May 05 07:26:03 forta-node systemd[1]: Stopped Erigon Node.
May 05 07:26:51 forta-node systemd[1]: Started Erigon Node.
May 05 07:26:51 forta-node erigon[58284]: [INFO] [05-05|07:26:51.833] Build info                               git_branch=devel git_tag=v2022.05.02 git_commit=77441916fd32957c7e40474559ffb204bbceff92
May 05 07:26:51 forta-node erigon[58284]: [INFO] [05-05|07:26:51.833] Starting Erigon on Ethereum mainnet...
May 05 07:26:51 forta-node erigon[58284]: [INFO] [05-05|07:26:51.834] Maximum peer count                       ETH=100 total=100
May 05 07:26:53 forta-node erigon[58284]: [INFO] [05-05|07:26:53.938] Set global gas cap                       cap=50000000
May 05 07:26:53 forta-node erigon[58284]: [INFO] [05-05|07:26:53.996] Opening Database                         label=chaindata path=/root/erigon-data/chaindata
May 05 07:26:54 forta-node erigon[58284]: [INFO] [05-05|07:26:54.004] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Terminal Total Difficulty: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
May 05 07:26:54 forta-node erigon[58284]: [INFO] [05-05|07:26:54.689] Disk storage enabled for ethash DAGs     dir=/root/erigon-data/ethash-dags count=2
May 05 07:26:54 forta-node erigon[58284]: [INFO] [05-05|07:26:54.689] Initialising Ethereum protocol           network=1
May 05 07:26:54 forta-node erigon[58284]: [INFO] [05-05|07:26:54.689] Effective                                prune_flags="--prune=" snapshot_flags="--syncmode=snap"
May 05 07:26:54 forta-node erigon[58284]: [INFO] [05-05|07:26:54.740] Starting private RPC server              on=localhost:9090
May 05 07:26:54 forta-node erigon[58284]: [INFO] [05-05|07:26:54.740] new subscription to logs established
May 05 07:26:54 forta-node erigon[58284]: [INFO] [05-05|07:26:54.751] [Snapshots] Fetching torrent files metadata
May 05 07:26:54 forta-node erigon[58284]: [INFO] [05-05|07:26:54.752] Started P2P networking                   version=66 self=enode://f10dceea2a657a278e3cbe6cc2c69c3f68fdd0410ed3cb79323650ec0c886b12b011feca1b2deea9f405353a747f88dae627a37f2c3a98402c19287de0196536@127.0.0.1:30303 name=erigon/v2022.99.99-dev-77441916/linux-amd64/go1.18.1
May 05 07:26:55 forta-node erigon[58284]: [INFO] [05-05|07:26:55.068] new subscription to newHeaders established
May 05 07:26:55 forta-node erigon[58284]: [INFO] [05-05|07:26:55.068] New txs subscriber joined
May 05 07:27:01 forta-node erigon[58284]: [INFO] [05-05|07:27:01.418] [Snapshots] download                     progress="0.00% 0b/0b" download=0b/s upload=0b/s peers=0 connections=0 files=0 alloc=148.8Mb sys=207.2Mb
May 05 07:27:33 forta-node erigon[58284]: [INFO] [05-05|07:27:33.545] [1/16 Headers] Writing total difficulty index for snapshots block_num=2606580
May 05 07:27:53 forta-node erigon[58284]: [INFO] [05-05|07:27:53.545] [1/16 Headers] Writing total difficulty index for snapshots block_num=5439337
May 05 07:28:13 forta-node erigon[58284]: [INFO] [05-05|07:28:13.545] [1/16 Headers] Writing total difficulty index for snapshots block_num=8225851
May 05 07:28:33 forta-node erigon[58284]: [INFO] [05-05|07:28:33.545] [1/16 Headers] Writing total difficulty index for snapshots block_num=11002461
May 05 07:28:53 forta-node erigon[58284]: [INFO] [05-05|07:28:53.545] [1/16 Headers] Writing total difficulty index for snapshots block_num=13762156
May 05 07:28:54 forta-node erigon[58284]: [INFO] [05-05|07:28:54.005] [p2p] GoodPeers                          eth66=11
May 05 07:28:59 forta-node erigon[58284]: [INFO] [05-05|07:28:59.610] [1/16 Headers] Waiting for headers...    from=14499999
May 05 07:29:19 forta-node erigon[58284]: [INFO] [05-05|07:29:19.613] [1/16 Headers] Inserting headers         progress=14614286
May 05 07:29:39 forta-node erigon[58284]: [INFO] [05-05|07:29:39.612] [1/16 Headers] Inserting headers         progress=14620267
May 05 07:29:59 forta-node erigon[58284]: [INFO] [05-05|07:29:59.611] [1/16 Headers] Inserting headers         progress=14626261
May 05 07:30:19 forta-node erigon[58284]: [INFO] [05-05|07:30:19.610] [1/16 Headers] Inserting headers         progress=14632293
May 05 07:30:39 forta-node erigon[58284]: [INFO] [05-05|07:30:39.612] [1/16 Headers] Inserting headers         progress=14638340
May 05 07:30:54 forta-node erigon[58284]: [INFO] [05-05|07:30:54.005] [p2p] GoodPeers                          eth66=18
May 05 07:30:59 forta-node erigon[58284]: [INFO] [05-05|07:30:59.612] [1/16 Headers] Inserting headers         progress=14644130
May 05 07:31:19 forta-node erigon[58284]: [INFO] [05-05|07:31:19.613] [1/16 Headers] Inserting headers         progress=14649992
May 05 07:31:39 forta-node erigon[58284]: [INFO] [05-05|07:31:39.613] [1/16 Headers] Inserting headers         progress=14655805
May 05 07:31:59 forta-node erigon[58284]: [INFO] [05-05|07:31:59.611] [1/16 Headers] Inserting headers         progress=14661653
May 05 07:32:19 forta-node erigon[58284]: [INFO] [05-05|07:32:19.613] [1/16 Headers] Inserting headers         progress=14667511
May 05 07:32:39 forta-node erigon[58284]: [INFO] [05-05|07:32:39.611] [1/16 Headers] Inserting headers         progress=14673738
May 05 07:32:54 forta-node erigon[58284]: [INFO] [05-05|07:32:54.006] [p2p] GoodPeers                          eth66=26
May 05 07:32:59 forta-node erigon[58284]: [INFO] [05-05|07:32:59.612] [1/16 Headers] Inserting headers         progress=14680148
May 05 07:33:19 forta-node erigon[58284]: [INFO] [05-05|07:33:19.612] [1/16 Headers] Inserting headers         progress=14686556
May 05 07:33:39 forta-node erigon[58284]: [INFO] [05-05|07:33:39.611] [1/16 Headers] Inserting headers         progress=14692968
May 05 07:33:59 forta-node erigon[58284]: [INFO] [05-05|07:33:59.613] [1/16 Headers] Inserting headers         progress=14699479
May 05 07:34:19 forta-node erigon[58284]: [INFO] [05-05|07:34:19.612] [1/16 Headers] Inserting headers         progress=14705915
May 05 07:34:39 forta-node erigon[58284]: [INFO] [05-05|07:34:39.611] [1/16 Headers] Inserting headers         progress=14712401
May 05 07:34:48 forta-node erigon[58284]: [WARN] [05-05|07:34:48.970] Invalidating anchor                      height=13751916 hash=0xee3b0a7e67a512edf7a3c14a6a898fd3df1750de17c1fa3dc719e05d0328ea7b reason="anchor below preverified"
May 05 07:34:51 forta-node erigon[58284]: [INFO] [05-05|07:34:51.405] [1/16 Headers] Processed                 highest inserted=14715416 age=6m14s
May 05 07:34:51 forta-node erigon[58284]: [INFO] [05-05|07:34:51.405] [1/16 Headers] DONE                      in=7m56.653952359s
May 05 07:34:51 forta-node erigon[58284]: [INFO] [05-05|07:34:51.835] [4/16 Bodies] Processing bodies...       from=14499999 to=14715416
May 05 07:34:54 forta-node erigon[58284]: [INFO] [05-05|07:34:54.005] [p2p] GoodPeers                          eth66=31
May 05 07:35:11 forta-node erigon[58284]: [INFO] [05-05|07:35:11.836] [4/16 Bodies] Wrote block bodies         block_num=14500398 delivery/sec=118.5Mb wasted/sec=0b alloc=10.4Gb sys=16.1Gb
May 05 07:35:31 forta-node erigon[58284]: [INFO] [05-05|07:35:31.836] [4/16 Bodies] Wrote block bodies         block_num=14500828 delivery/sec=21.7Mb wasted/sec=0b alloc=12.2Gb sys=16.1Gb
May 05 07:35:51 forta-node erigon[58284]: [INFO] [05-05|07:35:51.835] [4/16 Bodies] Wrote block bodies         block_num=14500828 delivery/sec=1.3Mb wasted/sec=0b alloc=12.5Gb sys=16.1Gb
May 05 07:36:11 forta-node erigon[58284]: [INFO] [05-05|07:36:11.836] [4/16 Bodies] Wrote block bodies         block_num=14500874 delivery/sec=1.6Mb wasted/sec=0b alloc=12.9Gb sys=16.1Gb
May 05 07:36:31 forta-node erigon[58284]: [INFO] [05-05|07:36:31.836] [4/16 Bodies] Wrote block bodies         block_num=14500920 delivery/sec=508.4Kb wasted/sec=0b alloc=13.2Gb sys=16.1Gb
May 05 07:36:51 forta-node erigon[58284]: [INFO] [05-05|07:36:51.835] [4/16 Bodies] Wrote block bodies         block_num=14500920 delivery/sec=0b wasted/sec=0b alloc=13.4Gb sys=16.1Gb
May 05 07:36:54 forta-node erigon[58284]: [INFO] [05-05|07:36:54.005] [p2p] GoodPeers                          eth66=44
May 05 07:37:11 forta-node erigon[58284]: [INFO] [05-05|07:37:11.835] [4/16 Bodies] Wrote block bodies         block_num=14511996 delivery/sec=44.2Mb wasted/sec=0b alloc=10.3Gb sys=17.3Gb
May 05 07:37:37 forta-node erigon[58284]: [INFO] [05-05|07:37:37.644] [4/16 Bodies] Wrote block bodies         block_num=14533954 delivery/sec=2.1Mb wasted/sec=0b alloc=11.0Gb sys=17.3Gb
May 05 07:37:51 forta-node erigon[58284]: [INFO] [05-05|07:37:51.847] [4/16 Bodies] Wrote block bodies         block_num=14533954 delivery/sec=82.6Mb wasted/sec=0b alloc=17.2Gb sys=18.2Gb
May 05 07:38:13 forta-node erigon[58284]: [INFO] [05-05|07:38:13.657] [4/16 Bodies] Wrote block bodies         block_num=14545129 delivery/sec=24.8Mb wasted/sec=0b alloc=10.4Gb sys=19.9Gb
May 05 07:38:31 forta-node erigon[58284]: [INFO] [05-05|07:38:31.836] [4/16 Bodies] Wrote block bodies         block_num=14545129 delivery/sec=41.0Mb wasted/sec=0b alloc=13.5Gb sys=19.9Gb
May 05 07:38:51 forta-node erigon[58284]: [INFO] [05-05|07:38:51.975] [4/16 Bodies] Wrote block bodies         block_num=14558576 delivery/sec=11.6Mb wasted/sec=0b alloc=14.8Gb sys=19.9Gb
May 05 07:38:54 forta-node erigon[58284]: [INFO] [05-05|07:38:54.005] [p2p] GoodPeers                          eth66=52
May 05 07:39:17 forta-node erigon[58284]: [INFO] [05-05|07:39:17.864] [4/16 Bodies] Wrote block bodies         block_num=14578443 delivery/sec=46.5Mb wasted/sec=0b alloc=18.8Gb sys=19.9Gb
May 05 07:39:32 forta-node erigon[58284]: [INFO] [05-05|07:39:32.248] [4/16 Bodies] Wrote block bodies         block_num=14582041 delivery/sec=87.1Mb wasted/sec=0b alloc=14.2Gb sys=20.3Gb
May 05 07:39:51 forta-node erigon[58284]: [INFO] [05-05|07:39:51.835] [4/16 Bodies] Wrote block bodies         block_num=14588230 delivery/sec=44.1Mb wasted/sec=0b alloc=11.3Gb sys=20.3Gb
May 05 07:40:11 forta-node erigon[58284]: [INFO] [05-05|07:40:11.835] [4/16 Bodies] Wrote block bodies         block_num=14605957 delivery/sec=63.4Mb wasted/sec=0b alloc=16.4Gb sys=20.3Gb
May 05 07:40:38 forta-node erigon[58284]: [INFO] [05-05|07:40:38.230] [4/16 Bodies] Wrote block bodies         block_num=14621085 delivery/sec=12.4Mb wasted/sec=0b alloc=17.9Gb sys=20.3Gb
May 05 07:40:53 forta-node erigon[58284]: [INFO] [05-05|07:40:53.191] [4/16 Bodies] Wrote block bodies         block_num=14626850 delivery/sec=67.3Mb wasted/sec=172.6Kb alloc=13.1Gb sys=20.3Gb
May 05 07:40:54 forta-node erigon[58284]: [INFO] [05-05|07:40:54.005] [p2p] GoodPeers                          eth66=57
May 05 07:41:11 forta-node erigon[58284]: [INFO] [05-05|07:41:11.837] [4/16 Bodies] Wrote block bodies         block_num=14627507 delivery/sec=30.1Mb wasted/sec=0b alloc=15.6Gb sys=20.3Gb
May 05 07:41:35 forta-node erigon[58284]: [INFO] [05-05|07:41:35.289] [4/16 Bodies] Wrote block bodies         block_num=14640748 delivery/sec=13.9Mb wasted/sec=0b alloc=9.8Gb sys=20.3Gb
May 05 07:41:51 forta-node erigon[58284]: [INFO] [05-05|07:41:51.894] [4/16 Bodies] Wrote block bodies         block_num=14647509 delivery/sec=39.0Mb wasted/sec=0b alloc=12.5Gb sys=20.3Gb
May 05 07:42:26 forta-node erigon[58284]: [INFO] [05-05|07:42:26.358] [4/16 Bodies] Wrote block bodies         block_num=14662163 delivery/sec=43.2Mb wasted/sec=0b alloc=16.3Gb sys=20.3Gb
May 05 07:42:34 forta-node erigon[58284]: [INFO] [05-05|07:42:34.518] [4/16 Bodies] Wrote block bodies         block_num=14664262 delivery/sec=31.3Mb wasted/sec=0b alloc=9.9Gb sys=20.3Gb
May 05 07:42:54 forta-node erigon[58284]: [INFO] [05-05|07:42:54.006] [p2p] GoodPeers                          eth66=57
May 05 07:42:56 forta-node erigon[58284]: [INFO] [05-05|07:42:56.408] [4/16 Bodies] Wrote block bodies         block_num=14670865 delivery/sec=27.2Mb wasted/sec=0b alloc=12.4Gb sys=20.3Gb
May 05 07:43:11 forta-node erigon[58284]: [INFO] [05-05|07:43:11.836] [4/16 Bodies] Wrote block bodies         block_num=14671490 delivery/sec=34.2Mb wasted/sec=0b alloc=14.9Gb sys=20.3Gb
May 05 07:43:31 forta-node erigon[58284]: [INFO] [05-05|07:43:31.835] [4/16 Bodies] Wrote block bodies         block_num=14671490 delivery/sec=2.3Mb wasted/sec=0b alloc=15.3Gb sys=20.3Gb
May 05 07:44:15 forta-node erigon[58284]: [INFO] [05-05|07:44:15.481] [4/16 Bodies] Wrote block bodies         block_num=14685910 delivery/sec=4.9Mb wasted/sec=0b alloc=16.4Gb sys=20.3Gb
May 05 07:44:54 forta-node erigon[58284]: [INFO] [05-05|07:44:54.006] [p2p] GoodPeers                          eth66=59
May 05 07:44:57 forta-node erigon[58284]: [INFO] [05-05|07:44:57.976] [4/16 Bodies] Wrote block bodies         block_num=14698734 delivery/sec=13.8Mb wasted/sec=660.9Kb alloc=9.4Gb sys=20.3Gb
May 05 07:45:22 forta-node erigon[58284]: [INFO] [05-05|07:45:22.849] [4/16 Bodies] Wrote block bodies         block_num=14704528 delivery/sec=18.3Mb wasted/sec=427.2Kb alloc=11.0Gb sys=20.3Gb
May 05 07:45:31 forta-node erigon[58284]: [INFO] [05-05|07:45:31.835] [4/16 Bodies] Wrote block bodies         block_num=14706536 delivery/sec=5.9Mb wasted/sec=236.1Kb alloc=11.4Gb sys=20.3Gb
May 05 07:45:51 forta-node erigon[58284]: [INFO] [05-05|07:45:51.836] [4/16 Bodies] Wrote block bodies         block_num=14707134 delivery/sec=4.1Mb wasted/sec=0b alloc=11.9Gb sys=20.3Gb
May 05 07:46:11 forta-node erigon[58284]: [INFO] [05-05|07:46:11.836] [4/16 Bodies] Wrote block bodies         block_num=14708053 delivery/sec=2.8Mb wasted/sec=0b alloc=12.4Gb sys=20.3Gb
May 05 07:46:31 forta-node erigon[58284]: [INFO] [05-05|07:46:31.836] [4/16 Bodies] Wrote block bodies         block_num=14708192 delivery/sec=49.8Kb wasted/sec=0b alloc=8.2Gb sys=20.3Gb
May 05 07:46:51 forta-node erigon[58284]: [INFO] [05-05|07:46:51.835] [4/16 Bodies] Wrote block bodies         block_num=14710869 delivery/sec=1.0Mb wasted/sec=0b alloc=7.9Gb sys=20.3Gb
May 05 07:46:54 forta-node erigon[58284]: [INFO] [05-05|07:46:54.005] [p2p] GoodPeers                          eth66=62
May 05 07:47:11 forta-node erigon[58284]: [INFO] [05-05|07:47:11.835] [4/16 Bodies] Wrote block bodies         block_num=14715137 delivery/sec=321.0Kb wasted/sec=0b alloc=8.1Gb sys=20.3Gb
May 05 07:48:54 forta-node erigon[58284]: [INFO] [05-05|07:48:54.005] [p2p] GoodPeers                          eth66=63
May 05 07:50:54 forta-node erigon[58284]: [INFO] [05-05|07:50:54.006] [p2p] GoodPeers                          eth66=64
May 05 07:52:28 forta-node erigon[58284]: [INFO] [05-05|07:52:28.888] [4/16 Bodies] Processed                  highest=14715416
May 05 07:52:28 forta-node erigon[58284]: [INFO] [05-05|07:52:28.889] [4/16 Bodies] DONE                       in=17m37.053872783s
May 05 07:52:28 forta-node erigon[58284]: [INFO] [05-05|07:52:28.889] [5/16 Senders] Started                   from=13119519 to=14715416
May 05 07:52:28 forta-node erigon[58284]: [INFO] [05-05|07:52:28.974] [6/16 Execution] Blocks execution        from=13119519 to=14715416
May 05 07:52:29 forta-node erigon[58284]: [EROR] [05-05|07:52:29.050] [6/16 Execution] Execution failed        block=13119520 hash=0x9d683102479c742b46e9647a8290615e86ecb92a83cdf2b8f2d6ed90c31c189b err="mismatched receipt headers for block 13119520"
May 05 07:52:29 forta-node erigon[58284]: [INFO] [05-05|07:52:29.050] UnwindTo                                 block=13119519 bad_block_hash=0x9d683102479c742b46e9647a8290615e86ecb92a83cdf2b8f2d6ed90c31c189b
May 05 07:52:29 forta-node erigon[58284]: [INFO] [05-05|07:52:29.050] [6/16 Execution] Completed on            block=13119519
May 05 07:52:50 forta-node erigon[58284]: [INFO] [05-05|07:52:50.607] [4/16 Bodies] Wrote block bodies         block_num=14499999 delivery/sec=0b wasted/sec=0b alloc=7.0Gb sys=20.3Gb
May 05 07:52:54 forta-node erigon[58284]: [INFO] [05-05|07:52:54.006] [p2p] GoodPeers                          eth66=70
May 05 07:53:10 forta-node erigon[58284]: [INFO] [05-05|07:53:10.606] [4/16 Bodies] Wrote block bodies         block_num=14499999 delivery/sec=0b wasted/sec=0b alloc=7.3Gb sys=20.3Gb
May 05 07:53:30 forta-node erigon[58284]: [INFO] [05-05|07:53:30.606] [4/16 Bodies] Wrote block bodies         block_num=14499999 delivery/sec=0b wasted/sec=0b alloc=7.5Gb sys=20.3Gb
May 05 07:53:50 forta-node erigon[58284]: [INFO] [05-05|07:53:50.606] [4/16 Bodies] Wrote block bodies         block_num=14499999 delivery/sec=0b wasted/sec=0b alloc=7.8Gb sys=20.3Gb
May 05 07:54:10 forta-node erigon[58284]: [INFO] [05-05|07:54:10.606] [4/16 Bodies] Wrote block bodies         block_num=14499999 delivery/sec=0b wasted/sec=0b alloc=8.0Gb sys=20.3Gb
May 05 07:54:10 forta-node erigon[58284]: [INFO] [05-05|07:54:10.612] [4/16 Bodies] DONE                       in=1m40.006360188s
May 05 07:54:10 forta-node erigon[58284]: [INFO] [05-05|07:54:10.612] [5/16 Senders] Started                   from=13119519 to=14499999
May 05 07:54:10 forta-node erigon[58284]: [INFO] [05-05|07:54:10.623] [6/16 Execution] Blocks execution        from=13119519 to=14499999
May 05 07:54:10 forta-node erigon[58284]: [EROR] [05-05|07:54:10.691] [6/16 Execution] Execution failed        block=13119520 hash=0x0000000000000000000000000000000000000000000000000000000000000000 err="mismatched receipt headers for block 13119520"
May 05 07:54:10 forta-node erigon[58284]: [INFO] [05-05|07:54:10.691] UnwindTo                                 block=13119519 bad_block_hash=0x0000000000000000000000000000000000000000000000000000000000000000
May 05 07:54:10 forta-node erigon[58284]: [INFO] [05-05|07:54:10.691] [6/16 Execution] Completed on            block=13119519
May 05 07:54:30 forta-node erigon[58284]: [INFO] [05-05|07:54:30.698] [1/16 Headers] Writing total difficulty index for snapshots block_num=2761551
May 05 07:54:50 forta-node erigon[58284]: [INFO] [05-05|07:54:50.698] [1/16 Headers] Writing total difficulty index for snapshots block_num=5576524
May 05 07:54:54 forta-node erigon[58284]: [INFO] [05-05|07:54:54.005] [p2p] GoodPeers                          eth66=75
May 05 07:55:10 forta-node erigon[58284]: [INFO] [05-05|07:55:10.699] [1/16 Headers] Writing total difficulty index for snapshots block_num=8400105
May 05 07:55:30 forta-node erigon[58284]: [INFO] [05-05|07:55:30.698] [1/16 Headers] Writing total difficulty index for snapshots block_num=11207485
May 05 07:55:50 forta-node erigon[58284]: [INFO] [05-05|07:55:50.698] [1/16 Headers] Writing total difficulty index for snapshots block_num=13946560
May 05 07:55:54 forta-node erigon[58284]: [INFO] [05-05|07:55:54.760] [1/16 Headers] Waiting for headers...    from=14499999
May 05 07:56:14 forta-node erigon[58284]: [INFO] [05-05|07:56:14.761] [1/16 Headers] Wrote block headers       number=14648991 blk/second=7449.600 alloc=11.0Gb sys=20.3Gb
May 05 07:56:14 forta-node erigon[58284]: [WARN] [05-05|07:56:14.776] Invalidating anchor                      height=14488669 hash=0xcd6555d0c26b7d6cea14eac79291e0cba06f0319697ce03ef1781de83f1a64b2 reason="anchor below preverified"
May 05 07:56:34 forta-node erigon[58284]: [INFO] [05-05|07:56:34.761] [1/16 Headers] Wrote block headers       number=14648991 blk/second=0.000 alloc=11.2Gb sys=20.3Gb
May 05 07:56:54 forta-node erigon[58284]: [INFO] [05-05|07:56:54.005] [p2p] GoodPeers                          eth66=74
May 05 07:56:54 forta-node erigon[58284]: [INFO] [05-05|07:56:54.761] [1/16 Headers] Wrote block headers       number=14648991 blk/second=0.000 alloc=11.5Gb sys=20.3Gb
May 05 07:57:14 forta-node erigon[58284]: [INFO] [05-05|07:57:14.761] [1/16 Headers] Wrote block headers       number=14648991 blk/second=0.000 alloc=11.8Gb sys=20.3Gb
May 05 07:57:34 forta-node erigon[58284]: [INFO] [05-05|07:57:34.761] [1/16 Headers] Wrote block headers       number=14648991 blk/second=0.000 alloc=12.1Gb sys=20.3Gb
May 05 07:57:54 forta-node erigon[58284]: [INFO] [05-05|07:57:54.761] [1/16 Headers] Wrote block headers       number=14648991 blk/second=0.000 alloc=6.9Gb sys=20.3Gb
May 05 07:58:14 forta-node erigon[58284]: [INFO] [05-05|07:58:14.766] [1/16 Headers] Wrote block headers       number=14648991 blk/second=0.000 alloc=7.2Gb sys=20.3Gb
May 05 07:58:34 forta-node erigon[58284]: [INFO] [05-05|07:58:34.761] [1/16 Headers] Wrote block headers       number=14648991 blk/second=0.000 alloc=7.4Gb sys=20.3Gb`

**Comment by AskAlexSharov** [comment]
let's try:
```
make integration
./build/bin/integration stage_exec --unwind=100 --datadir=<your_datadir> --chain=mainnet
```

**Comment by vanphandinh** [comment]
> 

okay, let me try.

**Comment by AskAlexSharov** [comment]
and next:
```
make downloader
./build/bin/downloader torrent_hashes --verify --datadir=<your_datadir>
```
```

**Comment by vanphandinh** [comment]
![Screen Shot 2022-05-05 at 2 24 26 PM](https://user-images.githubusercontent.com/13887599/166878661-28455c7c-2d87-4cce-947e-16522fc635ff.png)

Finished, waiting for the result.

**Comment by vanphandinh** [comment]
New update: 

![Screen Shot 2022-05-05 at 2 40 00 PM](https://user-images.githubusercontent.com/13887599/166880776-e5e9ad91-ccb0-44e8-8ed9-217825617aa1.png)

**Comment by vanphandinh** [comment]
![Screen Shot 2022-05-05 at 4 49 28 PM](https://user-images.githubusercontent.com/13887599/166900037-03aad571-4973-4aa5-b2f9-169f421ba9e7.png)

**Comment by AskAlexSharov** [comment]
hmmm... i don't have ideas yet. but have 2-nd complain about it. need some investigation.

**Comment by AskAlexSharov** [comment]
I see something new now: has=000000000
means something generally wrong with block itself - and need sear what's wrong with that block instead of search why we see another receipt hash after execution. 

Can you show: 
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber", "params": ["0xC83020", true], "id":1}' localhost:8545
```

**Comment by vanphandinh** [comment]
> 

Yes, the log file is here:
[log.txt](https://github.com/ledgerwatch/erigon/files/8638082/log.txt)

**Comment by AskAlexSharov** [comment]
Hi. Fixed in `devel` by https://github.com/ledgerwatch/erigon/pull/4087

**Comment by vanphandinh** [comment]
> Hi. Fixed in `devel` by #4087

Thanks, let me try to `git pull` & build the latest version.

**Comment by vanphandinh** [comment]
> Hi. Fixed in `devel` by #4087

It works, thank you 🙌
Begin the blocks execution        from=13119519 to=14722746

**Comment by garyrob** [comment]
Hello, I am having the same problem except it's stuck at block 14499999. Endless repeats of "[1/16 Headers] Wrote block headers       number=14499999 blk/second=0.000 alloc=7.4Gb sys=11.0Gb" with small differences in the last two numbers. I am using the latest devel release, git_commit=54076c9bcfb5670e8189e2698c7115b39ae9fd56. so, as I understand it, it should include the patch discussed above? Or am I missing something?

I don't know whether this is relevant, but before installing the latest release, I had a rapid infinite loop on a particular block saying something like "bad execution". This was while running an untagged devel release from a few days ago. I figured it might get fixed if I just upgrade to the latest devel release. So I did so, and now I'm in the loop described above.

If necessary I can delete all my data and re-sync from scratch, but I'd rather not!

**Comment by vanphandinh** [comment]
> Hello, I am having the same problem except it's stuck at block 14499999. Endless repeats of "[1/16 Headers] Wrote block headers number=14499999 blk/second=0.000 alloc=7.4Gb sys=11.0Gb" with small differences in the last two numbers. I am using the latest devel release, git_commit=54076c9bcfb5670e8189e2698c7115b39ae9fd56. so, as I understand it, it should include the patch discussed above? Or am I missing something?
> 
> I ran the erigon executable with no args—I didn't know any reason I shouldn't go with all the defaults.
> 
> I don't know whether this is relevant, but before installing the latest release, I had a rapid infinite loop on a particular block saying something like "bad execution". This was while running an untagged devel release from a few days ago. I figured it might get fixed if I just upgrade to the latest devel release. So I did so, and now I'm in the loop described above.
> 
> If necessary I can delete all my data and re-sync from scratch, but I'd rather not!

Have you tried to stop your erigon, run `git pull` and `make erigon` again, then start erigon??
