### ISSUE TITLE
The node data synchronization is abnormal, and the block is not updated

### ISSUE THREAD

**Issue by wetezos** [ledgerwatch/erigon#4204]
#### System information

Erigon version: `./erigon --version`
erigon version 2022.05.4-alpha-a9f3c67f
OS & Version: Windows/Linux/OSX
Linux version 4.15.0-163-generic (buildd@lcy01-amd64-021) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021

Server configuration:
Hetzner root:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/40154568/169262201-40915046-3a2d-4c90-ade2-4b9619f002b9.png">

Commit hash : 
`git branch
* (HEAD detached at v2022.05.04)`

#### Expected behaviour

`erigon --syncmode snap --http --ws --http.addr 10.0.0.12 --http.vhosts eth.rpc.local --snap.keepblocks=true`
#### Actual behaviour
The node data synchronization is abnormal, and the block is not updated The following is the node log

`May 19 11:27:12 Ubuntu-1804-bionic-64-minimal erigon[3982]: [WARN] [05-19|11:27:12.875] Served                                   conn=217.12.201.45:41516 method=eth_accounts reqid=1 t=29.365µs err="the method has been deprecated: eth_accounts"
May 19 11:27:15 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:27:15.094] [p2p] GoodPeers                          eth66=60
May 19 11:27:16 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:27:16.694] [1/16 Headers] Wrote block headers       number=14802417 blk/second=0.000 alloc=7.6Gb sys=10.1Gb
May 19 11:27:16 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:27:16.694] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=21433 skelMin=14803953 skelMax=14803953 resp=21461 respMin=14803953 respMax=14804195
May 19 11:27:36 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:27:36.693] [1/16 Headers] Wrote block headers       number=14802417 blk/second=0.000 alloc=8.0Gb sys=10.1Gb
May 19 11:27:36 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:27:36.693] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=21955 skelMin=14803953 skelMax=14803953 resp=21986 respMin=14803953 respMax=14804197
May 19 11:27:40 Ubuntu-1804-bionic-64-minimal erigon[3982]: [WARN] [05-19|11:27:40.214] Served                                   conn=139.162.8.59:33006 method=eth_accounts reqid=0 t=35.657µs err="the method has been deprecated: eth_accounts"
May 19 11:27:42 Ubuntu-1804-bionic-64-minimal erigon[3982]: [WARN] [05-19|11:27:42.046] Served                                   conn=91.232.30.206:43762 method=net_version reqid=67 t=12.313µs err="the method net_version does not exist/is not available"
May 19 11:27:49 Ubuntu-1804-bionic-64-minimal erigon[3982]: [WARN] [05-19|11:27:49.556] Served                                   conn=217.12.201.45:41534 method=eth_accounts reqid=1 t=26.39µs err="the method has been deprecated: eth_accounts"
May 19 11:27:56 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:27:56.693] [1/16 Headers] Wrote block headers       number=14802417 blk/second=0.000 alloc=8.2Gb sys=10.1Gb
May 19 11:27:56 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:27:56.693] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16268 skelMin=14803953 skelMax=14803953 resp=16272 respMin=14803953 respMax=14803953
May 19 11:28:16 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:28:16.694] [1/16 Headers] Wrote block headers       number=14802417 blk/second=0.000 alloc=8.6Gb sys=10.1Gb
May 19 11:28:16 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:28:16.694] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=18590 skelMin=14803953 skelMax=14803953 resp=18598 respMin=14803953 respMax=14804198
May 19 11:28:23 Ubuntu-1804-bionic-64-minimal erigon[3982]: [WARN] [05-19|11:28:23.020] Served                                   conn=139.162.6.55:57068 method=eth_sendTransaction reqid=0 t=36.749µs err="the method is currently not implemented: eth_sendTransaction"
May 19 11:28:26 Ubuntu-1804-bionic-64-minimal erigon[3982]: [WARN] [05-19|11:28:26.077] Served                                   conn=217.12.201.45:41552 method=eth_accounts reqid=1 t=44.072µs err="the method has been deprecated: eth_accounts"
May 19 11:28:36 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:28:36.694] [1/16 Headers] Wrote block headers       number=14802417 blk/second=0.000 alloc=7.0Gb sys=10.1Gb
May 19 11:28:36 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:28:36.694] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=16732 skelMin=14803953 skelMax=14803953 resp=16750 respMin=14803953 respMax=14804200
May 19 11:28:56 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:28:56.694] [1/16 Headers] Wrote block headers       number=14802417 blk/second=0.000 alloc=7.3Gb sys=10.1Gb
May 19 11:28:56 Ubuntu-1804-bionic-64-minimal erigon[3982]: [INFO] [05-19|11:28:56.694] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=21600 skelMin=14803953 skelMax=14803953 resp=21623 respMin=14803953 respMax=14804202
May 19 11:28:57 Ubuntu-1804-bionic-64-minimal erigon[3982]: [WARN] [05-19|11:28:57.173] Served                                   conn=185.82.216.158:38350 method=net_version reqid=67 t=10.46µs err="the method net_version does not exist/is not available"
May 19 11:29:02 Ubuntu-1804-bionic-64-minimal erigon[3982]: [WARN] [05-19|11:29:02.650] Served                                   conn=217.12.201.45:41572 method=eth_accounts reqid=1 t=29.645µs err="the method has been deprecated: eth_accounts"`

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
hi. we just released `2022.05.05-alpha` - please try, thank you

**Comment by wetezos** [comment]
> hi. we just released `2022.05.05-alpha` - please try, thank you
I upgraded it. After restarting, I still have this problem.

`May 19 15:23:05 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:23:05.226] [p2p] GoodPeers                          eth66=43
May 19 15:23:16 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:23:16.404] [1/16 Headers] Wrote block headers       number=14804917 blk/second=0.000 alloc=4.2Gb sys=9.0Gb
May 19 15:23:16 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:23:16.404] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=9 respMin=14805188 respMax=14805189
May 19 15:23:32 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:23:32.884] Served                                   conn=217.12.201.45:48960 method=eth_accounts reqid=1 t=25.057µs err="the method has been deprecated: eth_accounts"
May 19 15:23:36 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:23:36.403] [1/16 Headers] Wrote block headers       number=14804917 blk/second=0.000 alloc=4.3Gb sys=9.0Gb
May 19 15:23:36 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:23:36.403] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=11 respMin=14805189 respMax=14805192
May 19 15:23:56 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:23:56.404] [1/16 Headers] Wrote block headers       number=14804917 blk/second=0.000 alloc=4.4Gb sys=9.0Gb
May 19 15:23:56 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:23:56.404] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=10 respMin=14805193 respMax=14805194
May 19 15:24:09 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:24:09.742] Served                                   conn=217.12.201.45:48978 method=eth_accounts reqid=1 t=25.838µs err="the method has been deprecated: eth_accounts"
May 19 15:24:16 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:24:16.403] [1/16 Headers] Wrote block headers       number=14804917 blk/second=0.000 alloc=4.5Gb sys=9.0Gb
May 19 15:24:16 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:24:16.403] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=12 respMin=14805195 respMax=14805196
May 19 15:24:25 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:24:25.435] Served                                   conn=5.101.66.189:45000 method=net_version reqid=67 t=10.851µs err="the method net_version does not exist/is not available"
May 19 15:24:28 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:24:28.550] Served                                   conn=139.162.6.55:57376 method=eth_sendTransaction reqid=0 t=35.256µs err="the method is currently not implemented: eth_sendTransaction"
May 19 15:24:36 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:24:36.403] [1/16 Headers] Wrote block headers       number=14804917 blk/second=0.000 alloc=4.0Gb sys=9.0Gb
May 19 15:24:36 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:24:36.403] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=15 respMin=14805197 respMax=14805199
May 19 15:24:38 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:24:38.537] Served                                   conn=91.232.30.206:59106 method=net_version reqid=67 t=12.744µs err="the method net_version does not exist/is not available"
May 19 15:24:44 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:24:44.136] Served                                   conn=195.123.217.13:54874 method=net_version reqid=67 t=10.029µs err="the method net_version does not exist/is not available"
May 19 15:24:46 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:24:46.674] Served                                   conn=217.12.201.45:48996 method=eth_accounts reqid=1 t=23.985µs err="the method has been deprecated: eth_accounts"
May 19 15:24:56 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:24:56.403] [1/16 Headers] Wrote block headers       number=14804917 blk/second=0.000 alloc=4.1Gb sys=9.0Gb
May 19 15:24:56 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:24:56.403] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=12 respMin=14805200 respMax=14805203
May 19 15:24:59 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:24:59.696] Served                                   conn=139.162.8.59:34214 method=eth_accounts reqid=0 t=33.573µs err="the method has been deprecated: eth_accounts"
May 19 15:25:05 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:25:05.226] [p2p] GoodPeers                          eth66=43
May 19 15:25:16 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:25:16.403] [1/16 Headers] Wrote block headers       number=14804917 blk/second=0.000 alloc=4.2Gb sys=9.0Gb
May 19 15:25:16 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:25:16.403] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=11 respMin=14805204 respMax=14805205
May 19 15:25:23 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:25:23.492] Served                                   conn=217.12.201.45:49016 method=eth_accounts reqid=1 t=24.315µs err="the method has been deprecated: eth_accounts"
May 19 15:25:25 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:25:25.165] Served                                   conn=5.34.180.59:53328 method=net_version reqid=67 t=10.85µs err="the method net_version does not exist/is not available"
May 19 15:25:36 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:25:36.404] [1/16 Headers] Wrote block headers       number=14804917 blk/second=0.000 alloc=4.4Gb sys=9.0Gb
May 19 15:25:36 Ubuntu-1804-bionic-64-minimal erigon[26149]: [INFO] [05-19|15:25:36.404] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=0 skelMin=0 skelMax=0 resp=9 respMin=14805206 respMax=14805207
May 19 15:25:43 Ubuntu-1804-bionic-64-minimal erigon[26149]: [WARN] [05-19|15:25:43.339] Served`

**Comment by AskAlexSharov** [comment]
Use 3 tildas

**Comment by wetezos** [comment]
> 

Sorry, I don't understand what you mean

**Comment by AskAlexSharov** [comment]
@wetezos i'm about https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

don't know reason why your sync is stuck - yet. do:
1. `make integration`
2. show `./build/bin/integration print_stages --datadir=<your_datadir>`
3. try `./build/bin/integration stage_headers --reset --datadir=<your_datadir>`, then start erigon as usual and see if it still has troubles

**Comment by wetezos** [comment]
> @wetezos i'm about https://www.markdownguide.org/extended-syntax/#fenced-code-blocks
> 
> don't know reason why your sync is stuck - yet. do:
> 
> 1. `make integration`
> 2. show `./build/bin/integration print_stages --datadir=<your_datadir>`
> 3. try `./build/bin/integration stage_headers --reset --datadir=<your_datadir>`, then start erigon as usual and see if it still has troubles

Thanks a lot. It's ok now.
