### ISSUE TITLE
polygon: trace_block: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by joucksHua** [ledgerwatch/erigon#4963]
#### System information

Erigon version: `./erigon --version`
latest version
OS & Version: Windows/Linux/OSX
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

erigon cli:
```
./bin/erigon
--chain=bor-mainnet
--bor.heimdall=http://10.10.17.2:2327/
--torrent.download.rate=512mb
--torrent.upload.rate=6mb
--datadir=/opt/erigon-bor/data
--torrent.port=42069
--port=40306
--private.api.addr=localhost:9092
--http
--http.port=9547
--http.addr=10.10.17.4
--http.api=eth,erigon,web3,net,debug,trace,txpool
```
Commit hash : 
```
git_branch=devel git_tag=v2021.10.03-1617-g6d86b3a40-dirty git_commit=6d86b3a4031d9be007501eabb80ea38b844af72c
```
#### Expected behaviour
Make an HTTP request to the node, I want 13 transaction information
This is the request parameter
```
{
"jsonrpc": "2.0",
"method": "trace_block",
"params": ["0xa596e9"],
"id": 1
}
```

But an error is returned:
```
{
"jsonrpc": "2.0",
"id": 1,
"error": {
"code": -32000,
"message": "first run for txIndex 2 error: insufficient funds for gas * price + value: address 0x1CA971963bdb4BA2BF337c90660674AcFf5Beb3f have 1340837000000000 want 2808193000000000"
}
}
```
I hope the gods can work it out. Thank you！

**Comment by alangshur** [comment]
Noticing a similar error on post-merge Ethereum as well. If you do `trace_block` on block 15539505 or `trace_transaction` on `0x2fdf04a1d70c3cfa1f9d89baf080377ca110c5dbc28def63b01e18b270e85f6f`, you get the following error:

```
first run for txIndex 323 error: insufficient funds for gas * price + value: address 0xb64a30399f7F6b0C154c2E7Af0a3ec7B0A5b131a have 79011297267895730 want 79314366712002216
```

Running dedicated archive Erigon through Chainstack so wish I had more technical input to contribute but found this thread from the exact same Polygon trace issue referenced above and then just ran into it again on PoS Ethereum. Looks like a transaction was included that doesn't have enough eth?

**Comment by fabwa** [comment]
Fixed in v2022.09.02 it seems

**Comment by zimbabao** [comment]
I can still see this error for gnosis chain. 
I am running https://hub.docker.com/layers/thorax/erigon/stable/images/sha256-f03a8a4626f2afe95c38b6d2c900fa3d5e99bbc321a34840a7549c583c7a4b06?context=explore . 

```
Err: first run for txIndex 9 error: insufficient funds for gas * price + value: address 0xF4317f378c7879DfB75907Ee3e99260E40A20b14 have 509993134191999906922 want 1000006193840000000000
```
