### ISSUE TITLE
panic: upload rate limiter burst size < 16384

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#4980]
```
panic: upload rate limiter burst size < 16384
goroutine 9673 [running]:
github.com/anacrolix/torrent.(*PeerConn).upload(0xc0a1bc6d00, 0xc0a3347948)
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peerconn.go:1610 +0x574
github.com/anacrolix/torrent.(*PeerConn).fillWriteBuffer(0xc0a1bc6d00)
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peerconn.go:708 +0xea
github.com/anacrolix/torrent.(*PeerConn).initMessageWriter.func1()
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peer-conn-msg-writer.go:24 +0x107
github.com/anacrolix/torrent.(*peerConnMsgWriter).run(0xc0a1bc7140, 0xdf8475800)
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peer-conn-msg-writer.go:75 +0x12a
github.com/anacrolix/torrent.(*PeerConn).messageWriterRunner(0xc0a1bc6d00)
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peer-conn-msg-writer.go:47 +0x22f
created by github.com/anacrolix/torrent.(*PeerConn).startMessageWriter
	github.com/anacrolix/torrent@v1.46.1-0.20220713100403-caa9400c52fe/peer-conn-msg-writer.go:40 +0x97
```

**Comment by AskAlexSharov** [comment]
fixed

**Comment by brinzi** [comment]
im still seeing this on 2.36.0
panic: upload rate limiter burst size < 524288
```
panic: upload rate limiter burst size < 524288
goroutine 23205 [running]:
github.com/anacrolix/torrent.(*PeerConn).upload(0xc0b245f600, 0xc033113b40)
        github.com/anacrolix/torrent@v1.48.0/peerconn.go:1620 +0x3b9
github.com/anacrolix/torrent.(*PeerConn).fillWriteBuffer(0xc0b245f600)
        github.com/anacrolix/torrent@v1.48.0/peerconn.go:713 +0x8f
github.com/anacrolix/torrent.(*PeerConn).initMessageWriter.func1()
        github.com/anacrolix/torrent@v1.48.0/peer-conn-msg-writer.go:24 +0xa6
github.com/anacrolix/torrent.(*peerConnMsgWriter).run(0xc0b245fa40, 0xdf8475800)
        github.com/anacrolix/torrent@v1.48.0/peer-conn-msg-writer.go:75 +0xe2
github.com/anacrolix/torrent.(*PeerConn).messageWriterRunner(0x3fdb8e0?)
        github.com/anacrolix/torrent@v1.48.0/peer-conn-msg-writer.go:47 +0xd8
created by github.com/anacrolix/torrent.(*PeerConn).startMessageWriter
        github.com/anacrolix/torrent@v1.48.0/peer-conn-msg-writer.go:40 +0x5b
```

**Comment by AskAlexSharov** [comment]
related https://github.com/anacrolix/torrent/issues/793
