### ISSUE TITLE
Erigon is not pulling the most recent blocks

### ISSUE THREAD

**Issue by Bulat-Gumerov** [ledgerwatch/erigon#7036]
#### System information
Running ETH mainnet archive node on the AWS EKS
Erigon version: 2.39.0
Node succesfully finished syncing process previously.
Erigon Command (with flags/config):
`exec erigon --datadir=/data --nat=extip:$(POD_IP) --port=30303
          --http=false --private.api.addr=127.0.0.1:9090
          --authrpc.jwtsecret=/data/jwt.hex --authrpc.addr=0.0.0.0
          --authrpc.port=8551 --authrpc.vhosts=* --metrics
          --metrics.addr=0.0.0.0 --metrics.port=6060 --chain=mainnet
          --maxpeers=600 --torrent.maxpeers=1000 --torrent.conns.perfile=100
          --torrent.download.rate=20gb --torrent.upload.rate=10kb
          --http.addr=0.0.0.0 --http.port=10001 --http.trace=true
          --http.api=net,eth,erigon,engine,debug,trace,web3
          --snap.keepblocks=true --ws=true --ws.compression=true`
RPC daemon Command:
`while ! nc -z 127.0.0.1 9090; do sleep 1; done; exec rpcdaemon
--datadir=/data --private.api.addr=127.0.0.1:9090
--txpool.api.addr=127.0.0.1:9090 --http.addr=0.0.0.0 --http.port=8545
--http.vhosts=* --metrics --metrics.addr=0.0.0.0 --metrics.port=6061`

#### Chain/Network: 
ETH mainnet

Sometimes Erigon gets stuck on my archive node and not pulling the most recent blocks.
In the logs below we can see that it's stuck on the block number 16769134, but the most recent safe block is 16770343(at the time of writing this):
https://pastebin.com/7mUSWwse
Restarting Erigon helps to fix this issue temporarily and then after some time this happens again.

**Comment by AlexeyAkhunov** [comment]
This should be fixed in v2.40.0

**Comment by ygaberman-px** [comment]
Upgraded to v2.40.1 and not seeing this issue anymore

**Comment by ygaberman-px** [comment]
Disregard that, this is still happening (erigon falling behind / getting stuck on a block)

**Comment by AskAlexSharov** [comment]
> Disregard that, this is still happening (erigon falling behind / getting stuck on a block)

no logs - no honey

**Comment by yerazy** [comment]
> > Disregard that, this is still happening (erigon falling behind / getting stuck on a block)
> 
> no logs - no honey

I have a similar problem. Maybe it should work like that, I don’t know, but getting new blocks is very long. How to immediately receive new blocks in rpc?

2.39.0-dev-54c9d3e2 from the first rpc notification of new headers to the second - 16 minutes and 179 blocks. 26 minutes passed from the second one and new blocks were not registered, then I turned it off.
2.40.0-dev-157a380b with handling new payload until first rpc notification of new headers - 1 hour and 495 blocks. and from the second rpc notification to the third - 2 hours and 607 blocks. from the last rpc notification to shutdown - 37 minutes and 185 blocks, no new blocks were recorded.

<details>
  <summary>from log 2.40.0-dev-157a380b</summary>
  
```
first - INFO[03-15|16:25:36.190] [2/15 Headers] Handling new payload      height=16833576
INFO[03-15|17:26:23.239] RPC Daemon notified of new headers       from=16833345 to=16833840 hash=0xacf52568cefada22fa6adc1ba90a059f81af5af90967a15fa8ffb89096712c80 header sending=564µs log sending=0s
INFO[03-15|17:31:03.118] RPC Daemon notified of new headers       from=16833840 to=16833892 hash=0x0c7ad2e2fdfb21e970061359fc8c3e600a8fcf380922089c9667e221158d0bd8 header sending=0s log sending=0s
INFO[03-15|19:38:57.877] RPC Daemon notified of new headers       from=16833892 to=16834499 hash=0x9f6aca233bbd6646f3f8e20cf8404a7ac41631615a48bde50bf84bc3850f4977 header sending=1.1664ms log sending=0s
INFO[03-15|19:45:29.814] RPC Daemon notified of new headers       from=16834499 to=16834560 hash=0xf144a080f5214f097d10344263bbc27ae505beee384b12dd6b66955b8a720e57 header sending=0s log sending=0s
INFO[03-15|19:46:21.357] RPC Daemon notified of new headers       from=16834560 to=16834568 hash=0x18a077a8dc980b9e32f679f0acd97c69c0c4672775b4cf87b69849ff5c5b4ea5 header sending=0s log sending=0s
last - INFO[03-15|20:23:00.544] [2/15 Headers] Handling new payload      height=16834753
```

  
</details>

[1-log  2.39.0-dev-54c9d3e2.txt](https://github.com/ledgerwatch/erigon/files/10988362/1-log.2.39.0-dev-54c9d3e2.txt)
[2-log  2.40.0-dev-157a380b.txt](https://github.com/ledgerwatch/erigon/files/10988363/2-log.2.40.0-dev-157a380b.txt)

**Comment by arccos2x** [comment]
I am running 3 fnodes (all prune set to 100) on 2.31.0-stable, all 3 nodes started suffering from inability to retain canonical chain tip.

`{"level":"info","message":"[periodic block call] success, host: ws://eth-fnode-0:80, tip block: 16844384","timestamp":"2023-03-17T02:07:05.736Z"}
{"level":"info","message":"[periodic block call] success, host: ws://eth-fnode-1:80, tip block: 16844461","timestamp":"2023-03-17T02:07:05.764Z"}
{"level":"info","message":"[periodic block call] success, host: ws://eth-fnode-2:80, tip block: 16844403","timestamp":"2023-03-17T02:07:05.980Z"}`

this has been happening for last 12 hours

**Comment by arccos2x** [comment]
> I am running 3 fnodes (all prune set to 100) on 2.31.0-stable, all 3 nodes started suffering from inability to retain canonical chain tip.

would it be possibly related to having only 1 peer on LighClient?

`Mar 17 02:51:30 ip-10-100-2-74 erigon[133269]: [INFO] [03-17|02:51:30.108] [LightClient] P2P                        peers=1`

**Comment by arccos2x** [comment]
> Have a look at https://github.com/ledgerwatch/erigon/issues/7077, there is a discussion there about peers...

thanks @keithchew had a look, defo thing I need to address...
