### ISSUE TITLE
Lack of state sync transaction traces

### ISSUE THREAD

**Issue by MRabenda** [ledgerwatch/erigon#7504]
At Polygon we can find transaction from null address to null address without gas used - for example in this block

https://polygonscan.com/txs?block=8337920
This transaction
https://polygonscan.com/tx/0xa1cdcf443e47e0fef9c7f817554bab12e84d5179c414c5caccbf136eb031a5bd

This transaction has receipt - but when we will call trace_transaction there is not response for it. I am not sure what this transaction is doing overall in Polygon - I am guessing that this could be in-protocol bridge
# Rationale

Rewards etc are available via traces (trace_transactions as well as debug_traceTransaction) - but the above transaction does not have anything in response to traces. I think this is incorrect and similar to other activities it should be available here. 

Above transaction is releasing logs which should be visible via debug_traceTransaction IMO specially that there is storage changes

**Comment by Zorato** [comment]
Any update on this one? We consider this issue as very important when using Erigon over Bor.

**Comment by MRabenda** [comment]
@AskAlexSharov is there a chance that someone will help to investigate this? Looks like that Erigon has overall issues with Polygon state sync transactions.

**Comment by 0xKrishna** [comment]
Okay, I think we recently inntroduced this feature in bor and I think @anshalshukla also ported that in erigon as well, Let us find the PR.

**Comment by 0xKrishna** [comment]
https://github.com/ledgerwatch/erigon/pull/6830

**Comment by MRabenda** [comment]
@0xKrishna question thanks, are state sync available for the entire history if using snapshots?

**Comment by 0xKrishna** [comment]
Not yet, We will soon release a snapshot with full state-sync history when used with `--snapshots=false`

**Comment by quickchase** [comment]
Running nodes with `--snapshots=false` contradicts the Erigon roadmap. Disabling them doesn't seem like a long-term solution.

**Comment by MRabenda** [comment]
I think it should not be stale

**Comment by Zorato** [comment]
Still waiting for Polygon mainnet erigon archive snapshot synced with disabled snapshots.

**Comment by quick-pawiromitchel** [comment]
bump

**Comment by dkatzan** [comment]
any updates on this?
we are facing this issue as well

**Comment by AskAlexSharov** [comment]
we released bor events snapshots: https://github.com/ledgerwatch/erigon/pull/7901 and https://github.com/ledgerwatch/erigon/pull/8065

As I understand - this is the solution. 

@mh0lt , right?

**Comment by quick-pawiromitchel** [comment]
bump

**Comment by quickchase** [comment]
This issue is only partially resolved, the behavior of `debug_traceBlockByNumber` seems to match bor now, both bor and erigon return the same number of traces, however, that number is "wrong"

Also `debug_traceTransaction` still returns `null` instead of `[]` as expected.

I downloaded the latest snapshot over at `snapshots.polygon.technology`, running the latest erigon.

Take this old state-sync transaction: `0xa1cdcf443e47e0fef9c7f817554bab12e84d5179c414c5caccbf136eb031a5bd`

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0xb681901447981864462b5bf3004814c436b308150e6369341524b6e215092676",
    "blockNumber": "0x7f3a00",
    "from": "0x0000000000000000000000000000000000000000",
    "gas": "0x0",
    "gasPrice": "0x0",
    "hash": "0xa1cdcf443e47e0fef9c7f817554bab12e84d5179c414c5caccbf136eb031a5bd",
    "input": "0x",
    "nonce": "0x0",
    "to": "0x0000000000000000000000000000000000000000",
    "transactionIndex": "0xa",
    "value": "0x0",
    "type": "0x0",
    "chainId": "0x89",
    "v": "0x0",
    "r": "0x0",
    "s": "0x0"
  }
}
```

Clearly I can get the transaction by hash now, that's good. I can also get the receipt (not shown). Awesome.

The transaction is in this block: `0x7f3a00` so let's get that block by number:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "difficulty": "0x6",
    "extraData": "0xd78301091883626f7288676f312e31352e35856c696e757800000000000000000e185bf9f43902f3d69b6b1b9614489338a94d983111a81cd97069ab9b6402393bd44cb45deb9a1e66cc4f744a1be3e2773c79a9a136b16beb91735e69cb03ed01",
    "gasLimit": "0x1312d00",
    "gasUsed": "0x11d8d9",
    "hash": "0xb681901447981864462b5bf3004814c436b308150e6369341524b6e215092676",
    "logsBloom": "0x00000000000008100000000000000000000800000000000000000800080000000000020004000000000000000100020000009000008000002800000400000000000000000000000000000008000000880020000080000000000300000000000000000000005000000000000000000001000000000000000080004010000000000000000002000000002004030000008000000000000000008000004200000020200008000000000000000000000000000000000000000000000000000000004000008002001000000001000010000000000400000010004002100181000008000100000000000000000000000000000000004001000008000000020000100000",
    "miner": "0x0000000000000000000000000000000000000000",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": "0x0000000000000000",
    "number": "0x7f3a00",
    "parentHash": "0xc4b0525d0958ef0edf91f22a2ee0971b5e3e232f9ec360b26219cd5b4441d312",
    "receiptsRoot": "0x829c60d2508495f47d83e59f4a3a38a4a3e5d01403d664c34aa4d3277996d772",
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "size": "0xfad",
    "stateRoot": "0x636f94dedcf4eac406daae53c3bc0af5cf184c900c4aa8200a50cf5fc70aefdd",
    "timestamp": "0x5fd90d52",
    "totalDifficulty": "0x349886a",
    "transactions": [
      "0x02f880f8b29c7611b25b6e8428937feb19a34fb62fc00697f13258ed85fda370",
      "0x3aea07a18f6f245e4d14d66c864c9d3885ecb2373335118da98f62c079da1aa7",
      "0x922d0ae11e86419c56560a1f346f01a1f87d01361934c3a83beea25503d5f43d",
      "0x1e320595051028582aad68f1c6b8a27295eb0f82e7e556826b2374dec4deb8b6",
      "0xcec85234abbff07845418df3ecea207754cd9ccb2264363225f216bcedc94f3e",
      "0xb35fad8492bbdbc357f615aba3580ff2169cfdfd403496d190bb11dc06e3912f",
      "0xf385fbae02d05ea0eabc8f62515e94ae06dbe27e8fba61db2b925ed3ff2b7386",
      "0x946359be42669e44bb300f45c10fa0b1d850637f1aa51cfa538e4b9f12f32543",
      "0x3895c05602d79e33231e3f9a60658b61704816801eea2da52b1ef6cbb04a13c8",
      "0xbed38c4b43d1f65053350cf0bb1f8d67cc81aeb65211d1bed87802a20a7732a9",
      "0xa1cdcf443e47e0fef9c7f817554bab12e84d5179c414c5caccbf136eb031a5bd"
    ],
    "transactionsRoot": "0xf8f1eef4de9a35dc8a391fb28126f41412868407a1d725edb2c0d102b9d07880",
    "uncles": []
  }
}
```

So far, so good, the state-sync transaction is there. However, let's look at traces...there are 11 transactions in this block so I would expect 11 top level traces, but I only get 10...

The thing is, I only get 10 in both Bor and Erigon, so from a compatibility perspective this is kinda fine, but also unexpected.

The thing that DOES differ between bor and erigon though is what happens if you do `debug_traceTransaction`:

Bor:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": []
}
```

Erigon:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": null
}
```

Hopefully this is helpful and can progress this issue to closure. I used to remember that bor returned the correct number of traces, but I just tested and it does not, so I don't know if Polygon changed that behavior. But we at least need to get a fix for `[]` vs `null`

**Comment by quickchase** [comment]
Additionally,

`eth_getBlockTransactionCountByNumber`

bor:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0xb"
}
```

Erigon:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0xa"
}
```

So this is also incorrect with Erigon

**Comment by taratorio** [comment]
@quickchase thank you for the input - im currently looking into fixing this and ill update you here on my progress over the next few days

**Comment by taratorio** [comment]
Update 
- https://github.com/ledgerwatch/erigon/pull/9267 adds support for bor state sync transactions in `debug_traceTransaction`, `debug_traceBlockByNumer`, `debug_traceBlockByHash` with `"borTraceEnabled": true` in the trace config param of the request (check PR for an example) in Erigon - tests look good
- @manav2401 will co-ordinate similar functionality in Bor if possible for compatibility

This should work both with --snapshots=true (default and recommended for Erigon) and --snapshots=false

**Comment by taratorio** [comment]
@quickchase thanks for reporting the issue with eth_getBlockTransactionCountByNumber
fix for it is here https://github.com/ledgerwatch/erigon/pull/9275

**Comment by taratorio** [comment]
support for tracing bor state sync events has been added in v2.58.0 and v 2.58.1
other reported issues should be resolved too
works with default erigon --snapshots=true
feel free to re-open if there's still issues with this
